// Code generated by ent, DO NOT EDIT.

package codexsetupgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldID, id))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldCodeHash, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldAPIKeyID, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldMode, v))
}

// ServerOrigin applies equality check predicate on the "server_origin" field. It's identical to ServerOriginEQ.
func ServerOrigin(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldServerOrigin, v))
}

// GatewayOrigin applies equality check predicate on the "gateway_origin" field. It's identical to GatewayOriginEQ.
func GatewayOrigin(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldGatewayOrigin, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContainsFold(FieldCodeHash, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContainsFold(FieldMode, v))
}

// ServerOriginEQ applies the EQ predicate on the "server_origin" field.
func ServerOriginEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldServerOrigin, v))
}

// ServerOriginNEQ applies the NEQ predicate on the "server_origin" field.
func ServerOriginNEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldServerOrigin, v))
}

// ServerOriginIn applies the In predicate on the "server_origin" field.
func ServerOriginIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldServerOrigin, vs...))
}

// ServerOriginNotIn applies the NotIn predicate on the "server_origin" field.
func ServerOriginNotIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldServerOrigin, vs...))
}

// ServerOriginGT applies the GT predicate on the "server_origin" field.
func ServerOriginGT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldServerOrigin, v))
}

// ServerOriginGTE applies the GTE predicate on the "server_origin" field.
func ServerOriginGTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldServerOrigin, v))
}

// ServerOriginLT applies the LT predicate on the "server_origin" field.
func ServerOriginLT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldServerOrigin, v))
}

// ServerOriginLTE applies the LTE predicate on the "server_origin" field.
func ServerOriginLTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldServerOrigin, v))
}

// ServerOriginContains applies the Contains predicate on the "server_origin" field.
func ServerOriginContains(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContains(FieldServerOrigin, v))
}

// ServerOriginHasPrefix applies the HasPrefix predicate on the "server_origin" field.
func ServerOriginHasPrefix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasPrefix(FieldServerOrigin, v))
}

// ServerOriginHasSuffix applies the HasSuffix predicate on the "server_origin" field.
func ServerOriginHasSuffix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasSuffix(FieldServerOrigin, v))
}

// ServerOriginEqualFold applies the EqualFold predicate on the "server_origin" field.
func ServerOriginEqualFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEqualFold(FieldServerOrigin, v))
}

// ServerOriginContainsFold applies the ContainsFold predicate on the "server_origin" field.
func ServerOriginContainsFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContainsFold(FieldServerOrigin, v))
}

// GatewayOriginEQ applies the EQ predicate on the "gateway_origin" field.
func GatewayOriginEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldGatewayOrigin, v))
}

// GatewayOriginNEQ applies the NEQ predicate on the "gateway_origin" field.
func GatewayOriginNEQ(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldGatewayOrigin, v))
}

// GatewayOriginIn applies the In predicate on the "gateway_origin" field.
func GatewayOriginIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldGatewayOrigin, vs...))
}

// GatewayOriginNotIn applies the NotIn predicate on the "gateway_origin" field.
func GatewayOriginNotIn(vs ...string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldGatewayOrigin, vs...))
}

// GatewayOriginGT applies the GT predicate on the "gateway_origin" field.
func GatewayOriginGT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldGatewayOrigin, v))
}

// GatewayOriginGTE applies the GTE predicate on the "gateway_origin" field.
func GatewayOriginGTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldGatewayOrigin, v))
}

// GatewayOriginLT applies the LT predicate on the "gateway_origin" field.
func GatewayOriginLT(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldGatewayOrigin, v))
}

// GatewayOriginLTE applies the LTE predicate on the "gateway_origin" field.
func GatewayOriginLTE(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldGatewayOrigin, v))
}

// GatewayOriginContains applies the Contains predicate on the "gateway_origin" field.
func GatewayOriginContains(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContains(FieldGatewayOrigin, v))
}

// GatewayOriginHasPrefix applies the HasPrefix predicate on the "gateway_origin" field.
func GatewayOriginHasPrefix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasPrefix(FieldGatewayOrigin, v))
}

// GatewayOriginHasSuffix applies the HasSuffix predicate on the "gateway_origin" field.
func GatewayOriginHasSuffix(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldHasSuffix(FieldGatewayOrigin, v))
}

// GatewayOriginEqualFold applies the EqualFold predicate on the "gateway_origin" field.
func GatewayOriginEqualFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEqualFold(FieldGatewayOrigin, v))
}

// GatewayOriginContainsFold applies the ContainsFold predicate on the "gateway_origin" field.
func GatewayOriginContainsFold(v string) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldContainsFold(FieldGatewayOrigin, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotNull(FieldConsumedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexSetupGrant) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexSetupGrant) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexSetupGrant) predicate.CodexSetupGrant {
	return predicate.CodexSetupGrant(sql.NotPredicates(p))
}
