// Code generated by ent, DO NOT EDIT.

package codexdevicetoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the codexdevicetoken type in the database.
	Label = "codex_device_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldRefreshTokenHash holds the string denoting the refresh_token_hash field in the database.
	FieldRefreshTokenHash = "refresh_token_hash"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRotatedAt holds the string denoting the rotated_at field in the database.
	FieldRotatedAt = "rotated_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the codexdevicetoken in the database.
	Table = "codex_device_tokens"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "codex_device_tokens"
	// DeviceInverseTable is the table name for the CodexManagedDevice entity.
	// It exists in this package in order to avoid circular dependency with the "codexmanageddevice" package.
	DeviceInverseTable = "codex_managed_devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
)

// Columns holds all SQL columns for codexdevicetoken fields.
var Columns = []string{
	FieldID,
	FieldDeviceID,
	FieldRefreshTokenHash,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldRotatedAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RefreshTokenHashValidator is a validator for the "refresh_token_hash" field. It is called by the builders before save.
	RefreshTokenHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CodexDeviceToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByRefreshTokenHash orders the results by the refresh_token_hash field.
func ByRefreshTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenHash, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRotatedAt orders the results by the rotated_at field.
func ByRotatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotatedAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
