// Code generated by ent, DO NOT EDIT.

package codexdevicetoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLTE(FieldID, id))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldDeviceID, v))
}

// RefreshTokenHash applies equality check predicate on the "refresh_token_hash" field. It's identical to RefreshTokenHashEQ.
func RefreshTokenHash(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldRefreshTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldCreatedAt, v))
}

// RotatedAt applies equality check predicate on the "rotated_at" field. It's identical to RotatedAtEQ.
func RotatedAt(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldRotatedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldRevokedAt, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...int64) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldDeviceID, vs...))
}

// RefreshTokenHashEQ applies the EQ predicate on the "refresh_token_hash" field.
func RefreshTokenHashEQ(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldRefreshTokenHash, v))
}

// RefreshTokenHashNEQ applies the NEQ predicate on the "refresh_token_hash" field.
func RefreshTokenHashNEQ(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldRefreshTokenHash, v))
}

// RefreshTokenHashIn applies the In predicate on the "refresh_token_hash" field.
func RefreshTokenHashIn(vs ...string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldRefreshTokenHash, vs...))
}

// RefreshTokenHashNotIn applies the NotIn predicate on the "refresh_token_hash" field.
func RefreshTokenHashNotIn(vs ...string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldRefreshTokenHash, vs...))
}

// RefreshTokenHashGT applies the GT predicate on the "refresh_token_hash" field.
func RefreshTokenHashGT(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGT(FieldRefreshTokenHash, v))
}

// RefreshTokenHashGTE applies the GTE predicate on the "refresh_token_hash" field.
func RefreshTokenHashGTE(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGTE(FieldRefreshTokenHash, v))
}

// RefreshTokenHashLT applies the LT predicate on the "refresh_token_hash" field.
func RefreshTokenHashLT(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLT(FieldRefreshTokenHash, v))
}

// RefreshTokenHashLTE applies the LTE predicate on the "refresh_token_hash" field.
func RefreshTokenHashLTE(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLTE(FieldRefreshTokenHash, v))
}

// RefreshTokenHashContains applies the Contains predicate on the "refresh_token_hash" field.
func RefreshTokenHashContains(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldContains(FieldRefreshTokenHash, v))
}

// RefreshTokenHashHasPrefix applies the HasPrefix predicate on the "refresh_token_hash" field.
func RefreshTokenHashHasPrefix(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldHasPrefix(FieldRefreshTokenHash, v))
}

// RefreshTokenHashHasSuffix applies the HasSuffix predicate on the "refresh_token_hash" field.
func RefreshTokenHashHasSuffix(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldHasSuffix(FieldRefreshTokenHash, v))
}

// RefreshTokenHashEqualFold applies the EqualFold predicate on the "refresh_token_hash" field.
func RefreshTokenHashEqualFold(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEqualFold(FieldRefreshTokenHash, v))
}

// RefreshTokenHashContainsFold applies the ContainsFold predicate on the "refresh_token_hash" field.
func RefreshTokenHashContainsFold(v string) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldContainsFold(FieldRefreshTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLTE(FieldCreatedAt, v))
}

// RotatedAtEQ applies the EQ predicate on the "rotated_at" field.
func RotatedAtEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldRotatedAt, v))
}

// RotatedAtNEQ applies the NEQ predicate on the "rotated_at" field.
func RotatedAtNEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldRotatedAt, v))
}

// RotatedAtIn applies the In predicate on the "rotated_at" field.
func RotatedAtIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldRotatedAt, vs...))
}

// RotatedAtNotIn applies the NotIn predicate on the "rotated_at" field.
func RotatedAtNotIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldRotatedAt, vs...))
}

// RotatedAtGT applies the GT predicate on the "rotated_at" field.
func RotatedAtGT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGT(FieldRotatedAt, v))
}

// RotatedAtGTE applies the GTE predicate on the "rotated_at" field.
func RotatedAtGTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGTE(FieldRotatedAt, v))
}

// RotatedAtLT applies the LT predicate on the "rotated_at" field.
func RotatedAtLT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLT(FieldRotatedAt, v))
}

// RotatedAtLTE applies the LTE predicate on the "rotated_at" field.
func RotatedAtLTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLTE(FieldRotatedAt, v))
}

// RotatedAtIsNil applies the IsNil predicate on the "rotated_at" field.
func RotatedAtIsNil() predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIsNull(FieldRotatedAt))
}

// RotatedAtNotNil applies the NotNil predicate on the "rotated_at" field.
func RotatedAtNotNil() predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotNull(FieldRotatedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.FieldNotNull(FieldRevokedAt))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.CodexManagedDevice) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexDeviceToken) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexDeviceToken) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexDeviceToken) predicate.CodexDeviceToken {
	return predicate.CodexDeviceToken(sql.NotPredicates(p))
}
