// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
)

// CodexDeviceToken is the model entity for the CodexDeviceToken schema.
type CodexDeviceToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID int64 `json:"device_id,omitempty"`
	// RefreshTokenHash holds the value of the "refresh_token_hash" field.
	RefreshTokenHash string `json:"refresh_token_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RotatedAt holds the value of the "rotated_at" field.
	RotatedAt *time.Time `json:"rotated_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CodexDeviceTokenQuery when eager-loading is set.
	Edges        CodexDeviceTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CodexDeviceTokenEdges holds the relations/edges for other nodes in the graph.
type CodexDeviceTokenEdges struct {
	// Device holds the value of the device edge.
	Device *CodexManagedDevice `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CodexDeviceTokenEdges) DeviceOrErr() (*CodexManagedDevice, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: codexmanageddevice.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexDeviceToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexdevicetoken.FieldID, codexdevicetoken.FieldDeviceID:
			values[i] = new(sql.NullInt64)
		case codexdevicetoken.FieldRefreshTokenHash:
			values[i] = new(sql.NullString)
		case codexdevicetoken.FieldExpiresAt, codexdevicetoken.FieldCreatedAt, codexdevicetoken.FieldRotatedAt, codexdevicetoken.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexDeviceToken fields.
func (_m *CodexDeviceToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexdevicetoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case codexdevicetoken.FieldDeviceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.Int64
			}
		case codexdevicetoken.FieldRefreshTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_hash", values[i])
			} else if value.Valid {
				_m.RefreshTokenHash = value.String
			}
		case codexdevicetoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case codexdevicetoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case codexdevicetoken.FieldRotatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rotated_at", values[i])
			} else if value.Valid {
				_m.RotatedAt = new(time.Time)
				*_m.RotatedAt = value.Time
			}
		case codexdevicetoken.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexDeviceToken.
// This includes values selected through modifiers, order, etc.
func (_m *CodexDeviceToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDevice queries the "device" edge of the CodexDeviceToken entity.
func (_m *CodexDeviceToken) QueryDevice() *CodexManagedDeviceQuery {
	return NewCodexDeviceTokenClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this CodexDeviceToken.
// Note that you need to call CodexDeviceToken.Unwrap() before calling this method if this CodexDeviceToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexDeviceToken) Update() *CodexDeviceTokenUpdateOne {
	return NewCodexDeviceTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexDeviceToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexDeviceToken) Unwrap() *CodexDeviceToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexDeviceToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexDeviceToken) String() string {
	var builder strings.Builder
	builder.WriteString("CodexDeviceToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("refresh_token_hash=")
	builder.WriteString(_m.RefreshTokenHash)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RotatedAt; v != nil {
		builder.WriteString("rotated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CodexDeviceTokens is a parsable slice of CodexDeviceToken.
type CodexDeviceTokens []*CodexDeviceToken
