// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexManagedDevice is the model entity for the CodexManagedDevice schema.
type CodexManagedDevice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Arch holds the value of the "arch" field.
	Arch string `json:"arch,omitempty"`
	// ManagerVersion holds the value of the "manager_version" field.
	ManagerVersion string `json:"manager_version,omitempty"`
	// Status holds the value of the "status" field.
	Status codexmanageddevice.Status `json:"status,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CodexManagedDeviceQuery when eager-loading is set.
	Edges        CodexManagedDeviceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CodexManagedDeviceEdges holds the relations/edges for other nodes in the graph.
type CodexManagedDeviceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Tokens holds the value of the tokens edge.
	Tokens []*CodexDeviceToken `json:"tokens,omitempty"`
	// AuditLogs holds the value of the audit_logs edge.
	AuditLogs []*CodexDeviceAuditLog `json:"audit_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CodexManagedDeviceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CodexManagedDeviceEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// TokensOrErr returns the Tokens value or an error if the edge
// was not loaded in eager-loading.
func (e CodexManagedDeviceEdges) TokensOrErr() ([]*CodexDeviceToken, error) {
	if e.loadedTypes[2] {
		return e.Tokens, nil
	}
	return nil, &NotLoadedError{edge: "tokens"}
}

// AuditLogsOrErr returns the AuditLogs value or an error if the edge
// was not loaded in eager-loading.
func (e CodexManagedDeviceEdges) AuditLogsOrErr() ([]*CodexDeviceAuditLog, error) {
	if e.loadedTypes[3] {
		return e.AuditLogs, nil
	}
	return nil, &NotLoadedError{edge: "audit_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexManagedDevice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexmanageddevice.FieldID, codexmanageddevice.FieldUserID, codexmanageddevice.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case codexmanageddevice.FieldName, codexmanageddevice.FieldPlatform, codexmanageddevice.FieldArch, codexmanageddevice.FieldManagerVersion, codexmanageddevice.FieldStatus:
			values[i] = new(sql.NullString)
		case codexmanageddevice.FieldCreatedAt, codexmanageddevice.FieldUpdatedAt, codexmanageddevice.FieldLastSeenAt, codexmanageddevice.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexManagedDevice fields.
func (_m *CodexManagedDevice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexmanageddevice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case codexmanageddevice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case codexmanageddevice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case codexmanageddevice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case codexmanageddevice.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case codexmanageddevice.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case codexmanageddevice.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case codexmanageddevice.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				_m.Arch = value.String
			}
		case codexmanageddevice.FieldManagerVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manager_version", values[i])
			} else if value.Valid {
				_m.ManagerVersion = value.String
			}
		case codexmanageddevice.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = codexmanageddevice.Status(value.String)
			}
		case codexmanageddevice.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = new(time.Time)
				*_m.LastSeenAt = value.Time
			}
		case codexmanageddevice.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexManagedDevice.
// This includes values selected through modifiers, order, etc.
func (_m *CodexManagedDevice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CodexManagedDevice entity.
func (_m *CodexManagedDevice) QueryUser() *UserQuery {
	return NewCodexManagedDeviceClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the CodexManagedDevice entity.
func (_m *CodexManagedDevice) QueryAPIKey() *APIKeyQuery {
	return NewCodexManagedDeviceClient(_m.config).QueryAPIKey(_m)
}

// QueryTokens queries the "tokens" edge of the CodexManagedDevice entity.
func (_m *CodexManagedDevice) QueryTokens() *CodexDeviceTokenQuery {
	return NewCodexManagedDeviceClient(_m.config).QueryTokens(_m)
}

// QueryAuditLogs queries the "audit_logs" edge of the CodexManagedDevice entity.
func (_m *CodexManagedDevice) QueryAuditLogs() *CodexDeviceAuditLogQuery {
	return NewCodexManagedDeviceClient(_m.config).QueryAuditLogs(_m)
}

// Update returns a builder for updating this CodexManagedDevice.
// Note that you need to call CodexManagedDevice.Unwrap() before calling this method if this CodexManagedDevice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexManagedDevice) Update() *CodexManagedDeviceUpdateOne {
	return NewCodexManagedDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexManagedDevice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexManagedDevice) Unwrap() *CodexManagedDevice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexManagedDevice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexManagedDevice) String() string {
	var builder strings.Builder
	builder.WriteString("CodexManagedDevice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(_m.Arch)
	builder.WriteString(", ")
	builder.WriteString("manager_version=")
	builder.WriteString(_m.ManagerVersion)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CodexManagedDevices is a parsable slice of CodexManagedDevice.
type CodexManagedDevices []*CodexManagedDevice
