// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexsetupgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexSetupGrantDelete is the builder for deleting a CodexSetupGrant entity.
type CodexSetupGrantDelete struct {
	config
	hooks    []Hook
	mutation *CodexSetupGrantMutation
}

// Where appends a list predicates to the CodexSetupGrantDelete builder.
func (_d *CodexSetupGrantDelete) Where(ps ...predicate.CodexSetupGrant) *CodexSetupGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CodexSetupGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexSetupGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CodexSetupGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codexsetupgrant.Table, sqlgraph.NewFieldSpec(codexsetupgrant.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CodexSetupGrantDeleteOne is the builder for deleting a single CodexSetupGrant entity.
type CodexSetupGrantDeleteOne struct {
	_d *CodexSetupGrantDelete
}

// Where appends a list predicates to the CodexSetupGrantDelete builder.
func (_d *CodexSetupGrantDeleteOne) Where(ps ...predicate.CodexSetupGrant) *CodexSetupGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CodexSetupGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codexsetupgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexSetupGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
