// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexDeviceTokenUpdate is the builder for updating CodexDeviceToken entities.
type CodexDeviceTokenUpdate struct {
	config
	hooks    []Hook
	mutation *CodexDeviceTokenMutation
}

// Where appends a list predicates to the CodexDeviceTokenUpdate builder.
func (_u *CodexDeviceTokenUpdate) Where(ps ...predicate.CodexDeviceToken) *CodexDeviceTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *CodexDeviceTokenUpdate) SetDeviceID(v int64) *CodexDeviceTokenUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdate) SetNillableDeviceID(v *int64) *CodexDeviceTokenUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *CodexDeviceTokenUpdate) SetRefreshTokenHash(v string) *CodexDeviceTokenUpdate {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdate) SetNillableRefreshTokenHash(v *string) *CodexDeviceTokenUpdate {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexDeviceTokenUpdate) SetExpiresAt(v time.Time) *CodexDeviceTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdate) SetNillableExpiresAt(v *time.Time) *CodexDeviceTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRotatedAt sets the "rotated_at" field.
func (_u *CodexDeviceTokenUpdate) SetRotatedAt(v time.Time) *CodexDeviceTokenUpdate {
	_u.mutation.SetRotatedAt(v)
	return _u
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdate) SetNillableRotatedAt(v *time.Time) *CodexDeviceTokenUpdate {
	if v != nil {
		_u.SetRotatedAt(*v)
	}
	return _u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (_u *CodexDeviceTokenUpdate) ClearRotatedAt() *CodexDeviceTokenUpdate {
	_u.mutation.ClearRotatedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *CodexDeviceTokenUpdate) SetRevokedAt(v time.Time) *CodexDeviceTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdate) SetNillableRevokedAt(v *time.Time) *CodexDeviceTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *CodexDeviceTokenUpdate) ClearRevokedAt() *CodexDeviceTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetDevice sets the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceTokenUpdate) SetDevice(v *CodexManagedDevice) *CodexDeviceTokenUpdate {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the CodexDeviceTokenMutation object of the builder.
func (_u *CodexDeviceTokenUpdate) Mutation() *CodexDeviceTokenMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceTokenUpdate) ClearDevice() *CodexDeviceTokenUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexDeviceTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexDeviceTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexDeviceTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexDeviceTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexDeviceTokenUpdate) check() error {
	if v, ok := _u.mutation.RefreshTokenHash(); ok {
		if err := codexdevicetoken.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceToken.refresh_token_hash": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexDeviceToken.device"`)
	}
	return nil
}

func (_u *CodexDeviceTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexdevicetoken.Table, codexdevicetoken.Columns, sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(codexdevicetoken.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexdevicetoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RotatedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldRotatedAt, field.TypeTime, value)
	}
	if _u.mutation.RotatedAtCleared() {
		_spec.ClearField(codexdevicetoken.FieldRotatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(codexdevicetoken.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdevicetoken.DeviceTable,
			Columns: []string{codexdevicetoken.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdevicetoken.DeviceTable,
			Columns: []string{codexdevicetoken.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexdevicetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexDeviceTokenUpdateOne is the builder for updating a single CodexDeviceToken entity.
type CodexDeviceTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexDeviceTokenMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *CodexDeviceTokenUpdateOne) SetDeviceID(v int64) *CodexDeviceTokenUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdateOne) SetNillableDeviceID(v *int64) *CodexDeviceTokenUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *CodexDeviceTokenUpdateOne) SetRefreshTokenHash(v string) *CodexDeviceTokenUpdateOne {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdateOne) SetNillableRefreshTokenHash(v *string) *CodexDeviceTokenUpdateOne {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexDeviceTokenUpdateOne) SetExpiresAt(v time.Time) *CodexDeviceTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *CodexDeviceTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRotatedAt sets the "rotated_at" field.
func (_u *CodexDeviceTokenUpdateOne) SetRotatedAt(v time.Time) *CodexDeviceTokenUpdateOne {
	_u.mutation.SetRotatedAt(v)
	return _u
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdateOne) SetNillableRotatedAt(v *time.Time) *CodexDeviceTokenUpdateOne {
	if v != nil {
		_u.SetRotatedAt(*v)
	}
	return _u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (_u *CodexDeviceTokenUpdateOne) ClearRotatedAt() *CodexDeviceTokenUpdateOne {
	_u.mutation.ClearRotatedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *CodexDeviceTokenUpdateOne) SetRevokedAt(v time.Time) *CodexDeviceTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *CodexDeviceTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *CodexDeviceTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *CodexDeviceTokenUpdateOne) ClearRevokedAt() *CodexDeviceTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetDevice sets the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceTokenUpdateOne) SetDevice(v *CodexManagedDevice) *CodexDeviceTokenUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the CodexDeviceTokenMutation object of the builder.
func (_u *CodexDeviceTokenUpdateOne) Mutation() *CodexDeviceTokenMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceTokenUpdateOne) ClearDevice() *CodexDeviceTokenUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// Where appends a list predicates to the CodexDeviceTokenUpdate builder.
func (_u *CodexDeviceTokenUpdateOne) Where(ps ...predicate.CodexDeviceToken) *CodexDeviceTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexDeviceTokenUpdateOne) Select(field string, fields ...string) *CodexDeviceTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexDeviceToken entity.
func (_u *CodexDeviceTokenUpdateOne) Save(ctx context.Context) (*CodexDeviceToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexDeviceTokenUpdateOne) SaveX(ctx context.Context) *CodexDeviceToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexDeviceTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexDeviceTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexDeviceTokenUpdateOne) check() error {
	if v, ok := _u.mutation.RefreshTokenHash(); ok {
		if err := codexdevicetoken.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceToken.refresh_token_hash": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexDeviceToken.device"`)
	}
	return nil
}

func (_u *CodexDeviceTokenUpdateOne) sqlSave(ctx context.Context) (_node *CodexDeviceToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexdevicetoken.Table, codexdevicetoken.Columns, sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexDeviceToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexdevicetoken.FieldID)
		for _, f := range fields {
			if !codexdevicetoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexdevicetoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(codexdevicetoken.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexdevicetoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RotatedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldRotatedAt, field.TypeTime, value)
	}
	if _u.mutation.RotatedAtCleared() {
		_spec.ClearField(codexdevicetoken.FieldRotatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(codexdevicetoken.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdevicetoken.DeviceTable,
			Columns: []string{codexdevicetoken.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdevicetoken.DeviceTable,
			Columns: []string{codexdevicetoken.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodexDeviceToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexdevicetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
