// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexDeviceTokenDelete is the builder for deleting a CodexDeviceToken entity.
type CodexDeviceTokenDelete struct {
	config
	hooks    []Hook
	mutation *CodexDeviceTokenMutation
}

// Where appends a list predicates to the CodexDeviceTokenDelete builder.
func (_d *CodexDeviceTokenDelete) Where(ps ...predicate.CodexDeviceToken) *CodexDeviceTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CodexDeviceTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexDeviceTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CodexDeviceTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codexdevicetoken.Table, sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CodexDeviceTokenDeleteOne is the builder for deleting a single CodexDeviceToken entity.
type CodexDeviceTokenDeleteOne struct {
	_d *CodexDeviceTokenDelete
}

// Where appends a list predicates to the CodexDeviceTokenDelete builder.
func (_d *CodexDeviceTokenDeleteOne) Where(ps ...predicate.CodexDeviceToken) *CodexDeviceTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CodexDeviceTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codexdevicetoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexDeviceTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
