// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
)

// CodexDeviceTokenCreate is the builder for creating a CodexDeviceToken entity.
type CodexDeviceTokenCreate struct {
	config
	mutation *CodexDeviceTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeviceID sets the "device_id" field.
func (_c *CodexDeviceTokenCreate) SetDeviceID(v int64) *CodexDeviceTokenCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_c *CodexDeviceTokenCreate) SetRefreshTokenHash(v string) *CodexDeviceTokenCreate {
	_c.mutation.SetRefreshTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CodexDeviceTokenCreate) SetExpiresAt(v time.Time) *CodexDeviceTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexDeviceTokenCreate) SetCreatedAt(v time.Time) *CodexDeviceTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexDeviceTokenCreate) SetNillableCreatedAt(v *time.Time) *CodexDeviceTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRotatedAt sets the "rotated_at" field.
func (_c *CodexDeviceTokenCreate) SetRotatedAt(v time.Time) *CodexDeviceTokenCreate {
	_c.mutation.SetRotatedAt(v)
	return _c
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_c *CodexDeviceTokenCreate) SetNillableRotatedAt(v *time.Time) *CodexDeviceTokenCreate {
	if v != nil {
		_c.SetRotatedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *CodexDeviceTokenCreate) SetRevokedAt(v time.Time) *CodexDeviceTokenCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *CodexDeviceTokenCreate) SetNillableRevokedAt(v *time.Time) *CodexDeviceTokenCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetDevice sets the "device" edge to the CodexManagedDevice entity.
func (_c *CodexDeviceTokenCreate) SetDevice(v *CodexManagedDevice) *CodexDeviceTokenCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the CodexDeviceTokenMutation object of the builder.
func (_c *CodexDeviceTokenCreate) Mutation() *CodexDeviceTokenMutation {
	return _c.mutation
}

// Save creates the CodexDeviceToken in the database.
func (_c *CodexDeviceTokenCreate) Save(ctx context.Context) (*CodexDeviceToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexDeviceTokenCreate) SaveX(ctx context.Context) *CodexDeviceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexDeviceTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexDeviceTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexDeviceTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexdevicetoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexDeviceTokenCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "CodexDeviceToken.device_id"`)}
	}
	if _, ok := _c.mutation.RefreshTokenHash(); !ok {
		return &ValidationError{Name: "refresh_token_hash", err: errors.New(`ent: missing required field "CodexDeviceToken.refresh_token_hash"`)}
	}
	if v, ok := _c.mutation.RefreshTokenHash(); ok {
		if err := codexdevicetoken.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceToken.refresh_token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CodexDeviceToken.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexDeviceToken.created_at"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "CodexDeviceToken.device"`)}
	}
	return nil
}

func (_c *CodexDeviceTokenCreate) sqlSave(ctx context.Context) (*CodexDeviceToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexDeviceTokenCreate) createSpec() (*CodexDeviceToken, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexDeviceToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexdevicetoken.Table, sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RefreshTokenHash(); ok {
		_spec.SetField(codexdevicetoken.FieldRefreshTokenHash, field.TypeString, value)
		_node.RefreshTokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(codexdevicetoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RotatedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldRotatedAt, field.TypeTime, value)
		_node.RotatedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(codexdevicetoken.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdevicetoken.DeviceTable,
			Columns: []string{codexdevicetoken.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexDeviceToken.Create().
//		SetDeviceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexDeviceTokenUpsert) {
//			SetDeviceID(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexDeviceTokenCreate) OnConflict(opts ...sql.ConflictOption) *CodexDeviceTokenUpsertOne {
	_c.conflict = opts
	return &CodexDeviceTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexDeviceToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexDeviceTokenCreate) OnConflictColumns(columns ...string) *CodexDeviceTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexDeviceTokenUpsertOne{
		create: _c,
	}
}

type (
	// CodexDeviceTokenUpsertOne is the builder for "upsert"-ing
	//  one CodexDeviceToken node.
	CodexDeviceTokenUpsertOne struct {
		create *CodexDeviceTokenCreate
	}

	// CodexDeviceTokenUpsert is the "OnConflict" setter.
	CodexDeviceTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeviceID sets the "device_id" field.
func (u *CodexDeviceTokenUpsert) SetDeviceID(v int64) *CodexDeviceTokenUpsert {
	u.Set(codexdevicetoken.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsert) UpdateDeviceID() *CodexDeviceTokenUpsert {
	u.SetExcluded(codexdevicetoken.FieldDeviceID)
	return u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (u *CodexDeviceTokenUpsert) SetRefreshTokenHash(v string) *CodexDeviceTokenUpsert {
	u.Set(codexdevicetoken.FieldRefreshTokenHash, v)
	return u
}

// UpdateRefreshTokenHash sets the "refresh_token_hash" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsert) UpdateRefreshTokenHash() *CodexDeviceTokenUpsert {
	u.SetExcluded(codexdevicetoken.FieldRefreshTokenHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexDeviceTokenUpsert) SetExpiresAt(v time.Time) *CodexDeviceTokenUpsert {
	u.Set(codexdevicetoken.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsert) UpdateExpiresAt() *CodexDeviceTokenUpsert {
	u.SetExcluded(codexdevicetoken.FieldExpiresAt)
	return u
}

// SetRotatedAt sets the "rotated_at" field.
func (u *CodexDeviceTokenUpsert) SetRotatedAt(v time.Time) *CodexDeviceTokenUpsert {
	u.Set(codexdevicetoken.FieldRotatedAt, v)
	return u
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsert) UpdateRotatedAt() *CodexDeviceTokenUpsert {
	u.SetExcluded(codexdevicetoken.FieldRotatedAt)
	return u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *CodexDeviceTokenUpsert) ClearRotatedAt() *CodexDeviceTokenUpsert {
	u.SetNull(codexdevicetoken.FieldRotatedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CodexDeviceTokenUpsert) SetRevokedAt(v time.Time) *CodexDeviceTokenUpsert {
	u.Set(codexdevicetoken.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsert) UpdateRevokedAt() *CodexDeviceTokenUpsert {
	u.SetExcluded(codexdevicetoken.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CodexDeviceTokenUpsert) ClearRevokedAt() *CodexDeviceTokenUpsert {
	u.SetNull(codexdevicetoken.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexDeviceToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexDeviceTokenUpsertOne) UpdateNewValues() *CodexDeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexdevicetoken.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexDeviceToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexDeviceTokenUpsertOne) Ignore() *CodexDeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexDeviceTokenUpsertOne) DoNothing() *CodexDeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexDeviceTokenCreate.OnConflict
// documentation for more info.
func (u *CodexDeviceTokenUpsertOne) Update(set func(*CodexDeviceTokenUpsert)) *CodexDeviceTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexDeviceTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *CodexDeviceTokenUpsertOne) SetDeviceID(v int64) *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertOne) UpdateDeviceID() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateDeviceID()
	})
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (u *CodexDeviceTokenUpsertOne) SetRefreshTokenHash(v string) *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetRefreshTokenHash(v)
	})
}

// UpdateRefreshTokenHash sets the "refresh_token_hash" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertOne) UpdateRefreshTokenHash() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateRefreshTokenHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexDeviceTokenUpsertOne) SetExpiresAt(v time.Time) *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertOne) UpdateExpiresAt() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetRotatedAt sets the "rotated_at" field.
func (u *CodexDeviceTokenUpsertOne) SetRotatedAt(v time.Time) *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetRotatedAt(v)
	})
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertOne) UpdateRotatedAt() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateRotatedAt()
	})
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *CodexDeviceTokenUpsertOne) ClearRotatedAt() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.ClearRotatedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CodexDeviceTokenUpsertOne) SetRevokedAt(v time.Time) *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertOne) UpdateRevokedAt() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CodexDeviceTokenUpsertOne) ClearRevokedAt() *CodexDeviceTokenUpsertOne {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *CodexDeviceTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexDeviceTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexDeviceTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexDeviceTokenUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexDeviceTokenUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexDeviceTokenCreateBulk is the builder for creating many CodexDeviceToken entities in bulk.
type CodexDeviceTokenCreateBulk struct {
	config
	err      error
	builders []*CodexDeviceTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexDeviceToken entities in the database.
func (_c *CodexDeviceTokenCreateBulk) Save(ctx context.Context) ([]*CodexDeviceToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexDeviceToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexDeviceTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexDeviceTokenCreateBulk) SaveX(ctx context.Context) []*CodexDeviceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexDeviceTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexDeviceTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexDeviceToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexDeviceTokenUpsert) {
//			SetDeviceID(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexDeviceTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexDeviceTokenUpsertBulk {
	_c.conflict = opts
	return &CodexDeviceTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexDeviceToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexDeviceTokenCreateBulk) OnConflictColumns(columns ...string) *CodexDeviceTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexDeviceTokenUpsertBulk{
		create: _c,
	}
}

// CodexDeviceTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexDeviceToken nodes.
type CodexDeviceTokenUpsertBulk struct {
	create *CodexDeviceTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexDeviceToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexDeviceTokenUpsertBulk) UpdateNewValues() *CodexDeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexdevicetoken.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexDeviceToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexDeviceTokenUpsertBulk) Ignore() *CodexDeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexDeviceTokenUpsertBulk) DoNothing() *CodexDeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexDeviceTokenCreateBulk.OnConflict
// documentation for more info.
func (u *CodexDeviceTokenUpsertBulk) Update(set func(*CodexDeviceTokenUpsert)) *CodexDeviceTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexDeviceTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *CodexDeviceTokenUpsertBulk) SetDeviceID(v int64) *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertBulk) UpdateDeviceID() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateDeviceID()
	})
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (u *CodexDeviceTokenUpsertBulk) SetRefreshTokenHash(v string) *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetRefreshTokenHash(v)
	})
}

// UpdateRefreshTokenHash sets the "refresh_token_hash" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertBulk) UpdateRefreshTokenHash() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateRefreshTokenHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexDeviceTokenUpsertBulk) SetExpiresAt(v time.Time) *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertBulk) UpdateExpiresAt() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetRotatedAt sets the "rotated_at" field.
func (u *CodexDeviceTokenUpsertBulk) SetRotatedAt(v time.Time) *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetRotatedAt(v)
	})
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertBulk) UpdateRotatedAt() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateRotatedAt()
	})
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *CodexDeviceTokenUpsertBulk) ClearRotatedAt() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.ClearRotatedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CodexDeviceTokenUpsertBulk) SetRevokedAt(v time.Time) *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CodexDeviceTokenUpsertBulk) UpdateRevokedAt() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CodexDeviceTokenUpsertBulk) ClearRevokedAt() *CodexDeviceTokenUpsertBulk {
	return u.Update(func(s *CodexDeviceTokenUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *CodexDeviceTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexDeviceTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexDeviceTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexDeviceTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
