// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexdeviceauditlog"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexDeviceAuditLogUpdate is the builder for updating CodexDeviceAuditLog entities.
type CodexDeviceAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *CodexDeviceAuditLogMutation
}

// Where appends a list predicates to the CodexDeviceAuditLogUpdate builder.
func (_u *CodexDeviceAuditLogUpdate) Where(ps ...predicate.CodexDeviceAuditLog) *CodexDeviceAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *CodexDeviceAuditLogUpdate) SetDeviceID(v int64) *CodexDeviceAuditLogUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdate) SetNillableDeviceID(v *int64) *CodexDeviceAuditLogUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CodexDeviceAuditLogUpdate) SetUserID(v int64) *CodexDeviceAuditLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdate) SetNillableUserID(v *int64) *CodexDeviceAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEvent sets the "event" field.
func (_u *CodexDeviceAuditLogUpdate) SetEvent(v string) *CodexDeviceAuditLogUpdate {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdate) SetNillableEvent(v *string) *CodexDeviceAuditLogUpdate {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *CodexDeviceAuditLogUpdate) SetIP(v string) *CodexDeviceAuditLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdate) SetNillableIP(v *string) *CodexDeviceAuditLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *CodexDeviceAuditLogUpdate) SetUserAgent(v string) *CodexDeviceAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdate) SetNillableUserAgent(v *string) *CodexDeviceAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *CodexDeviceAuditLogUpdate) SetMetadata(v map[string]interface{}) *CodexDeviceAuditLogUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CodexDeviceAuditLogUpdate) SetUser(v *User) *CodexDeviceAuditLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetDevice sets the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceAuditLogUpdate) SetDevice(v *CodexManagedDevice) *CodexDeviceAuditLogUpdate {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the CodexDeviceAuditLogMutation object of the builder.
func (_u *CodexDeviceAuditLogUpdate) Mutation() *CodexDeviceAuditLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CodexDeviceAuditLogUpdate) ClearUser() *CodexDeviceAuditLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDevice clears the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceAuditLogUpdate) ClearDevice() *CodexDeviceAuditLogUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexDeviceAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexDeviceAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexDeviceAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexDeviceAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexDeviceAuditLogUpdate) check() error {
	if v, ok := _u.mutation.Event(); ok {
		if err := codexdeviceauditlog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceAuditLog.event": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := codexdeviceauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceAuditLog.ip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexDeviceAuditLog.user"`)
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexDeviceAuditLog.device"`)
	}
	return nil
}

func (_u *CodexDeviceAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexdeviceauditlog.Table, codexdeviceauditlog.Columns, sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(codexdeviceauditlog.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(codexdeviceauditlog.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(codexdeviceauditlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(codexdeviceauditlog.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexdeviceauditlog.UserTable,
			Columns: []string{codexdeviceauditlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexdeviceauditlog.UserTable,
			Columns: []string{codexdeviceauditlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdeviceauditlog.DeviceTable,
			Columns: []string{codexdeviceauditlog.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdeviceauditlog.DeviceTable,
			Columns: []string{codexdeviceauditlog.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexdeviceauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexDeviceAuditLogUpdateOne is the builder for updating a single CodexDeviceAuditLog entity.
type CodexDeviceAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexDeviceAuditLogMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *CodexDeviceAuditLogUpdateOne) SetDeviceID(v int64) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdateOne) SetNillableDeviceID(v *int64) *CodexDeviceAuditLogUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CodexDeviceAuditLogUpdateOne) SetUserID(v int64) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdateOne) SetNillableUserID(v *int64) *CodexDeviceAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEvent sets the "event" field.
func (_u *CodexDeviceAuditLogUpdateOne) SetEvent(v string) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdateOne) SetNillableEvent(v *string) *CodexDeviceAuditLogUpdateOne {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *CodexDeviceAuditLogUpdateOne) SetIP(v string) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdateOne) SetNillableIP(v *string) *CodexDeviceAuditLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *CodexDeviceAuditLogUpdateOne) SetUserAgent(v string) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *CodexDeviceAuditLogUpdateOne) SetNillableUserAgent(v *string) *CodexDeviceAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *CodexDeviceAuditLogUpdateOne) SetMetadata(v map[string]interface{}) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CodexDeviceAuditLogUpdateOne) SetUser(v *User) *CodexDeviceAuditLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetDevice sets the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceAuditLogUpdateOne) SetDevice(v *CodexManagedDevice) *CodexDeviceAuditLogUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the CodexDeviceAuditLogMutation object of the builder.
func (_u *CodexDeviceAuditLogUpdateOne) Mutation() *CodexDeviceAuditLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CodexDeviceAuditLogUpdateOne) ClearUser() *CodexDeviceAuditLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDevice clears the "device" edge to the CodexManagedDevice entity.
func (_u *CodexDeviceAuditLogUpdateOne) ClearDevice() *CodexDeviceAuditLogUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// Where appends a list predicates to the CodexDeviceAuditLogUpdate builder.
func (_u *CodexDeviceAuditLogUpdateOne) Where(ps ...predicate.CodexDeviceAuditLog) *CodexDeviceAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexDeviceAuditLogUpdateOne) Select(field string, fields ...string) *CodexDeviceAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexDeviceAuditLog entity.
func (_u *CodexDeviceAuditLogUpdateOne) Save(ctx context.Context) (*CodexDeviceAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexDeviceAuditLogUpdateOne) SaveX(ctx context.Context) *CodexDeviceAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexDeviceAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexDeviceAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexDeviceAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Event(); ok {
		if err := codexdeviceauditlog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceAuditLog.event": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := codexdeviceauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceAuditLog.ip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexDeviceAuditLog.user"`)
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexDeviceAuditLog.device"`)
	}
	return nil
}

func (_u *CodexDeviceAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *CodexDeviceAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexdeviceauditlog.Table, codexdeviceauditlog.Columns, sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexDeviceAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexdeviceauditlog.FieldID)
		for _, f := range fields {
			if !codexdeviceauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexdeviceauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(codexdeviceauditlog.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(codexdeviceauditlog.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(codexdeviceauditlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(codexdeviceauditlog.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexdeviceauditlog.UserTable,
			Columns: []string{codexdeviceauditlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexdeviceauditlog.UserTable,
			Columns: []string{codexdeviceauditlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdeviceauditlog.DeviceTable,
			Columns: []string{codexdeviceauditlog.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdeviceauditlog.DeviceTable,
			Columns: []string{codexdeviceauditlog.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodexDeviceAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexdeviceauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
