// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/codexdeviceauditlog"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexManagedDeviceQuery is the builder for querying CodexManagedDevice entities.
type CodexManagedDeviceQuery struct {
	config
	ctx           *QueryContext
	order         []codexmanageddevice.OrderOption
	inters        []Interceptor
	predicates    []predicate.CodexManagedDevice
	withUser      *UserQuery
	withAPIKey    *APIKeyQuery
	withTokens    *CodexDeviceTokenQuery
	withAuditLogs *CodexDeviceAuditLogQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CodexManagedDeviceQuery builder.
func (_q *CodexManagedDeviceQuery) Where(ps ...predicate.CodexManagedDevice) *CodexManagedDeviceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CodexManagedDeviceQuery) Limit(limit int) *CodexManagedDeviceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CodexManagedDeviceQuery) Offset(offset int) *CodexManagedDeviceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CodexManagedDeviceQuery) Unique(unique bool) *CodexManagedDeviceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CodexManagedDeviceQuery) Order(o ...codexmanageddevice.OrderOption) *CodexManagedDeviceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *CodexManagedDeviceQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codexmanageddevice.Table, codexmanageddevice.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, codexmanageddevice.UserTable, codexmanageddevice.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAPIKey chains the current query on the "api_key" edge.
func (_q *CodexManagedDeviceQuery) QueryAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codexmanageddevice.Table, codexmanageddevice.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, codexmanageddevice.APIKeyTable, codexmanageddevice.APIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTokens chains the current query on the "tokens" edge.
func (_q *CodexManagedDeviceQuery) QueryTokens() *CodexDeviceTokenQuery {
	query := (&CodexDeviceTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codexmanageddevice.Table, codexmanageddevice.FieldID, selector),
			sqlgraph.To(codexdevicetoken.Table, codexdevicetoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, codexmanageddevice.TokensTable, codexmanageddevice.TokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuditLogs chains the current query on the "audit_logs" edge.
func (_q *CodexManagedDeviceQuery) QueryAuditLogs() *CodexDeviceAuditLogQuery {
	query := (&CodexDeviceAuditLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codexmanageddevice.Table, codexmanageddevice.FieldID, selector),
			sqlgraph.To(codexdeviceauditlog.Table, codexdeviceauditlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, codexmanageddevice.AuditLogsTable, codexmanageddevice.AuditLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CodexManagedDevice entity from the query.
// Returns a *NotFoundError when no CodexManagedDevice was found.
func (_q *CodexManagedDeviceQuery) First(ctx context.Context) (*CodexManagedDevice, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{codexmanageddevice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) FirstX(ctx context.Context) *CodexManagedDevice {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CodexManagedDevice ID from the query.
// Returns a *NotFoundError when no CodexManagedDevice ID was found.
func (_q *CodexManagedDeviceQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{codexmanageddevice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CodexManagedDevice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CodexManagedDevice entity is found.
// Returns a *NotFoundError when no CodexManagedDevice entities are found.
func (_q *CodexManagedDeviceQuery) Only(ctx context.Context) (*CodexManagedDevice, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{codexmanageddevice.Label}
	default:
		return nil, &NotSingularError{codexmanageddevice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) OnlyX(ctx context.Context) *CodexManagedDevice {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CodexManagedDevice ID in the query.
// Returns a *NotSingularError when more than one CodexManagedDevice ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CodexManagedDeviceQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{codexmanageddevice.Label}
	default:
		err = &NotSingularError{codexmanageddevice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CodexManagedDevices.
func (_q *CodexManagedDeviceQuery) All(ctx context.Context) ([]*CodexManagedDevice, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CodexManagedDevice, *CodexManagedDeviceQuery]()
	return withInterceptors[[]*CodexManagedDevice](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) AllX(ctx context.Context) []*CodexManagedDevice {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CodexManagedDevice IDs.
func (_q *CodexManagedDeviceQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(codexmanageddevice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CodexManagedDeviceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CodexManagedDeviceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CodexManagedDeviceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CodexManagedDeviceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CodexManagedDeviceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CodexManagedDeviceQuery) Clone() *CodexManagedDeviceQuery {
	if _q == nil {
		return nil
	}
	return &CodexManagedDeviceQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]codexmanageddevice.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.CodexManagedDevice{}, _q.predicates...),
		withUser:      _q.withUser.Clone(),
		withAPIKey:    _q.withAPIKey.Clone(),
		withTokens:    _q.withTokens.Clone(),
		withAuditLogs: _q.withAuditLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodexManagedDeviceQuery) WithUser(opts ...func(*UserQuery)) *CodexManagedDeviceQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodexManagedDeviceQuery) WithAPIKey(opts ...func(*APIKeyQuery)) *CodexManagedDeviceQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKey = query
	return _q
}

// WithTokens tells the query-builder to eager-load the nodes that are connected to
// the "tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodexManagedDeviceQuery) WithTokens(opts ...func(*CodexDeviceTokenQuery)) *CodexManagedDeviceQuery {
	query := (&CodexDeviceTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTokens = query
	return _q
}

// WithAuditLogs tells the query-builder to eager-load the nodes that are connected to
// the "audit_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodexManagedDeviceQuery) WithAuditLogs(opts ...func(*CodexDeviceAuditLogQuery)) *CodexManagedDeviceQuery {
	query := (&CodexDeviceAuditLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuditLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CodexManagedDevice.Query().
//		GroupBy(codexmanageddevice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CodexManagedDeviceQuery) GroupBy(field string, fields ...string) *CodexManagedDeviceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CodexManagedDeviceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = codexmanageddevice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CodexManagedDevice.Query().
//		Select(codexmanageddevice.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CodexManagedDeviceQuery) Select(fields ...string) *CodexManagedDeviceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CodexManagedDeviceSelect{CodexManagedDeviceQuery: _q}
	sbuild.label = codexmanageddevice.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CodexManagedDeviceSelect configured with the given aggregations.
func (_q *CodexManagedDeviceQuery) Aggregate(fns ...AggregateFunc) *CodexManagedDeviceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CodexManagedDeviceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !codexmanageddevice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CodexManagedDeviceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CodexManagedDevice, error) {
	var (
		nodes       = []*CodexManagedDevice{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withAPIKey != nil,
			_q.withTokens != nil,
			_q.withAuditLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CodexManagedDevice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CodexManagedDevice{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *CodexManagedDevice, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAPIKey; query != nil {
		if err := _q.loadAPIKey(ctx, query, nodes, nil,
			func(n *CodexManagedDevice, e *APIKey) { n.Edges.APIKey = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTokens; query != nil {
		if err := _q.loadTokens(ctx, query, nodes,
			func(n *CodexManagedDevice) { n.Edges.Tokens = []*CodexDeviceToken{} },
			func(n *CodexManagedDevice, e *CodexDeviceToken) { n.Edges.Tokens = append(n.Edges.Tokens, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAuditLogs; query != nil {
		if err := _q.loadAuditLogs(ctx, query, nodes,
			func(n *CodexManagedDevice) { n.Edges.AuditLogs = []*CodexDeviceAuditLog{} },
			func(n *CodexManagedDevice, e *CodexDeviceAuditLog) { n.Edges.AuditLogs = append(n.Edges.AuditLogs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CodexManagedDeviceQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CodexManagedDevice, init func(*CodexManagedDevice), assign func(*CodexManagedDevice, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CodexManagedDevice)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CodexManagedDeviceQuery) loadAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*CodexManagedDevice, init func(*CodexManagedDevice), assign func(*CodexManagedDevice, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CodexManagedDevice)
	for i := range nodes {
		fk := nodes[i].APIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CodexManagedDeviceQuery) loadTokens(ctx context.Context, query *CodexDeviceTokenQuery, nodes []*CodexManagedDevice, init func(*CodexManagedDevice), assign func(*CodexManagedDevice, *CodexDeviceToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*CodexManagedDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(codexdevicetoken.FieldDeviceID)
	}
	query.Where(predicate.CodexDeviceToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(codexmanageddevice.TokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CodexManagedDeviceQuery) loadAuditLogs(ctx context.Context, query *CodexDeviceAuditLogQuery, nodes []*CodexManagedDevice, init func(*CodexManagedDevice), assign func(*CodexManagedDevice, *CodexDeviceAuditLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*CodexManagedDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(codexdeviceauditlog.FieldDeviceID)
	}
	query.Where(predicate.CodexDeviceAuditLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(codexmanageddevice.AuditLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CodexManagedDeviceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CodexManagedDeviceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(codexmanageddevice.Table, codexmanageddevice.Columns, sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexmanageddevice.FieldID)
		for i := range fields {
			if fields[i] != codexmanageddevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(codexmanageddevice.FieldUserID)
		}
		if _q.withAPIKey != nil {
			_spec.Node.AddColumnOnce(codexmanageddevice.FieldAPIKeyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CodexManagedDeviceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(codexmanageddevice.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = codexmanageddevice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CodexManagedDeviceQuery) ForUpdate(opts ...sql.LockOption) *CodexManagedDeviceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CodexManagedDeviceQuery) ForShare(opts ...sql.LockOption) *CodexManagedDeviceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CodexManagedDeviceGroupBy is the group-by builder for CodexManagedDevice entities.
type CodexManagedDeviceGroupBy struct {
	selector
	build *CodexManagedDeviceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CodexManagedDeviceGroupBy) Aggregate(fns ...AggregateFunc) *CodexManagedDeviceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CodexManagedDeviceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodexManagedDeviceQuery, *CodexManagedDeviceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CodexManagedDeviceGroupBy) sqlScan(ctx context.Context, root *CodexManagedDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CodexManagedDeviceSelect is the builder for selecting fields of CodexManagedDevice entities.
type CodexManagedDeviceSelect struct {
	*CodexManagedDeviceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CodexManagedDeviceSelect) Aggregate(fns ...AggregateFunc) *CodexManagedDeviceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CodexManagedDeviceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodexManagedDeviceQuery, *CodexManagedDeviceSelect](ctx, _s.CodexManagedDeviceQuery, _s, _s.inters, v)
}

func (_s *CodexManagedDeviceSelect) sqlScan(ctx context.Context, root *CodexManagedDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
