// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/codexdeviceauditlog"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexManagedDeviceCreate is the builder for creating a CodexManagedDevice entity.
type CodexManagedDeviceCreate struct {
	config
	mutation *CodexManagedDeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexManagedDeviceCreate) SetCreatedAt(v time.Time) *CodexManagedDeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexManagedDeviceCreate) SetNillableCreatedAt(v *time.Time) *CodexManagedDeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CodexManagedDeviceCreate) SetUpdatedAt(v time.Time) *CodexManagedDeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CodexManagedDeviceCreate) SetNillableUpdatedAt(v *time.Time) *CodexManagedDeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CodexManagedDeviceCreate) SetUserID(v int64) *CodexManagedDeviceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *CodexManagedDeviceCreate) SetAPIKeyID(v int64) *CodexManagedDeviceCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CodexManagedDeviceCreate) SetName(v string) *CodexManagedDeviceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *CodexManagedDeviceCreate) SetPlatform(v string) *CodexManagedDeviceCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetArch sets the "arch" field.
func (_c *CodexManagedDeviceCreate) SetArch(v string) *CodexManagedDeviceCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetManagerVersion sets the "manager_version" field.
func (_c *CodexManagedDeviceCreate) SetManagerVersion(v string) *CodexManagedDeviceCreate {
	_c.mutation.SetManagerVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CodexManagedDeviceCreate) SetStatus(v codexmanageddevice.Status) *CodexManagedDeviceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CodexManagedDeviceCreate) SetNillableStatus(v *codexmanageddevice.Status) *CodexManagedDeviceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *CodexManagedDeviceCreate) SetLastSeenAt(v time.Time) *CodexManagedDeviceCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *CodexManagedDeviceCreate) SetNillableLastSeenAt(v *time.Time) *CodexManagedDeviceCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *CodexManagedDeviceCreate) SetRevokedAt(v time.Time) *CodexManagedDeviceCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *CodexManagedDeviceCreate) SetNillableRevokedAt(v *time.Time) *CodexManagedDeviceCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CodexManagedDeviceCreate) SetUser(v *User) *CodexManagedDeviceCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *CodexManagedDeviceCreate) SetAPIKey(v *APIKey) *CodexManagedDeviceCreate {
	return _c.SetAPIKeyID(v.ID)
}

// AddTokenIDs adds the "tokens" edge to the CodexDeviceToken entity by IDs.
func (_c *CodexManagedDeviceCreate) AddTokenIDs(ids ...int64) *CodexManagedDeviceCreate {
	_c.mutation.AddTokenIDs(ids...)
	return _c
}

// AddTokens adds the "tokens" edges to the CodexDeviceToken entity.
func (_c *CodexManagedDeviceCreate) AddTokens(v ...*CodexDeviceToken) *CodexManagedDeviceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTokenIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the CodexDeviceAuditLog entity by IDs.
func (_c *CodexManagedDeviceCreate) AddAuditLogIDs(ids ...int64) *CodexManagedDeviceCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the CodexDeviceAuditLog entity.
func (_c *CodexManagedDeviceCreate) AddAuditLogs(v ...*CodexDeviceAuditLog) *CodexManagedDeviceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// Mutation returns the CodexManagedDeviceMutation object of the builder.
func (_c *CodexManagedDeviceCreate) Mutation() *CodexManagedDeviceMutation {
	return _c.mutation
}

// Save creates the CodexManagedDevice in the database.
func (_c *CodexManagedDeviceCreate) Save(ctx context.Context) (*CodexManagedDevice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexManagedDeviceCreate) SaveX(ctx context.Context) *CodexManagedDevice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexManagedDeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexManagedDeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexManagedDeviceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexmanageddevice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := codexmanageddevice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := codexmanageddevice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexManagedDeviceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexManagedDevice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CodexManagedDevice.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CodexManagedDevice.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "CodexManagedDevice.api_key_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CodexManagedDevice.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := codexmanageddevice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "CodexManagedDevice.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := codexmanageddevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "CodexManagedDevice.arch"`)}
	}
	if v, ok := _c.mutation.Arch(); ok {
		if err := codexmanageddevice.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.arch": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManagerVersion(); !ok {
		return &ValidationError{Name: "manager_version", err: errors.New(`ent: missing required field "CodexManagedDevice.manager_version"`)}
	}
	if v, ok := _c.mutation.ManagerVersion(); ok {
		if err := codexmanageddevice.ManagerVersionValidator(v); err != nil {
			return &ValidationError{Name: "manager_version", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.manager_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CodexManagedDevice.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := codexmanageddevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CodexManagedDevice.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "CodexManagedDevice.api_key"`)}
	}
	return nil
}

func (_c *CodexManagedDeviceCreate) sqlSave(ctx context.Context) (*CodexManagedDevice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexManagedDeviceCreate) createSpec() (*CodexManagedDevice, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexManagedDevice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexmanageddevice.Table, sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(codexmanageddevice.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(codexmanageddevice.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(codexmanageddevice.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.ManagerVersion(); ok {
		_spec.SetField(codexmanageddevice.FieldManagerVersion, field.TypeString, value)
		_node.ManagerVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(codexmanageddevice.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(codexmanageddevice.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.UserTable,
			Columns: []string{codexmanageddevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.APIKeyTable,
			Columns: []string{codexmanageddevice.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexManagedDevice.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexManagedDeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexManagedDeviceCreate) OnConflict(opts ...sql.ConflictOption) *CodexManagedDeviceUpsertOne {
	_c.conflict = opts
	return &CodexManagedDeviceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexManagedDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexManagedDeviceCreate) OnConflictColumns(columns ...string) *CodexManagedDeviceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexManagedDeviceUpsertOne{
		create: _c,
	}
}

type (
	// CodexManagedDeviceUpsertOne is the builder for "upsert"-ing
	//  one CodexManagedDevice node.
	CodexManagedDeviceUpsertOne struct {
		create *CodexManagedDeviceCreate
	}

	// CodexManagedDeviceUpsert is the "OnConflict" setter.
	CodexManagedDeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexManagedDeviceUpsert) SetUpdatedAt(v time.Time) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateUpdatedAt() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CodexManagedDeviceUpsert) SetUserID(v int64) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateUserID() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *CodexManagedDeviceUpsert) SetAPIKeyID(v int64) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateAPIKeyID() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldAPIKeyID)
	return u
}

// SetName sets the "name" field.
func (u *CodexManagedDeviceUpsert) SetName(v string) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateName() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *CodexManagedDeviceUpsert) SetPlatform(v string) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdatePlatform() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldPlatform)
	return u
}

// SetArch sets the "arch" field.
func (u *CodexManagedDeviceUpsert) SetArch(v string) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldArch, v)
	return u
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateArch() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldArch)
	return u
}

// SetManagerVersion sets the "manager_version" field.
func (u *CodexManagedDeviceUpsert) SetManagerVersion(v string) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldManagerVersion, v)
	return u
}

// UpdateManagerVersion sets the "manager_version" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateManagerVersion() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldManagerVersion)
	return u
}

// SetStatus sets the "status" field.
func (u *CodexManagedDeviceUpsert) SetStatus(v codexmanageddevice.Status) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateStatus() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldStatus)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *CodexManagedDeviceUpsert) SetLastSeenAt(v time.Time) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateLastSeenAt() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *CodexManagedDeviceUpsert) ClearLastSeenAt() *CodexManagedDeviceUpsert {
	u.SetNull(codexmanageddevice.FieldLastSeenAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CodexManagedDeviceUpsert) SetRevokedAt(v time.Time) *CodexManagedDeviceUpsert {
	u.Set(codexmanageddevice.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsert) UpdateRevokedAt() *CodexManagedDeviceUpsert {
	u.SetExcluded(codexmanageddevice.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CodexManagedDeviceUpsert) ClearRevokedAt() *CodexManagedDeviceUpsert {
	u.SetNull(codexmanageddevice.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexManagedDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexManagedDeviceUpsertOne) UpdateNewValues() *CodexManagedDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexmanageddevice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexManagedDevice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexManagedDeviceUpsertOne) Ignore() *CodexManagedDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexManagedDeviceUpsertOne) DoNothing() *CodexManagedDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexManagedDeviceCreate.OnConflict
// documentation for more info.
func (u *CodexManagedDeviceUpsertOne) Update(set func(*CodexManagedDeviceUpsert)) *CodexManagedDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexManagedDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexManagedDeviceUpsertOne) SetUpdatedAt(v time.Time) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateUpdatedAt() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CodexManagedDeviceUpsertOne) SetUserID(v int64) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateUserID() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *CodexManagedDeviceUpsertOne) SetAPIKeyID(v int64) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateAPIKeyID() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetName sets the "name" field.
func (u *CodexManagedDeviceUpsertOne) SetName(v string) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateName() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *CodexManagedDeviceUpsertOne) SetPlatform(v string) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdatePlatform() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdatePlatform()
	})
}

// SetArch sets the "arch" field.
func (u *CodexManagedDeviceUpsertOne) SetArch(v string) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetArch(v)
	})
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateArch() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateArch()
	})
}

// SetManagerVersion sets the "manager_version" field.
func (u *CodexManagedDeviceUpsertOne) SetManagerVersion(v string) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetManagerVersion(v)
	})
}

// UpdateManagerVersion sets the "manager_version" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateManagerVersion() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateManagerVersion()
	})
}

// SetStatus sets the "status" field.
func (u *CodexManagedDeviceUpsertOne) SetStatus(v codexmanageddevice.Status) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateStatus() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *CodexManagedDeviceUpsertOne) SetLastSeenAt(v time.Time) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateLastSeenAt() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *CodexManagedDeviceUpsertOne) ClearLastSeenAt() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CodexManagedDeviceUpsertOne) SetRevokedAt(v time.Time) *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertOne) UpdateRevokedAt() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CodexManagedDeviceUpsertOne) ClearRevokedAt() *CodexManagedDeviceUpsertOne {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *CodexManagedDeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexManagedDeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexManagedDeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexManagedDeviceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexManagedDeviceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexManagedDeviceCreateBulk is the builder for creating many CodexManagedDevice entities in bulk.
type CodexManagedDeviceCreateBulk struct {
	config
	err      error
	builders []*CodexManagedDeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexManagedDevice entities in the database.
func (_c *CodexManagedDeviceCreateBulk) Save(ctx context.Context) ([]*CodexManagedDevice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexManagedDevice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexManagedDeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexManagedDeviceCreateBulk) SaveX(ctx context.Context) []*CodexManagedDevice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexManagedDeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexManagedDeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexManagedDevice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexManagedDeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexManagedDeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexManagedDeviceUpsertBulk {
	_c.conflict = opts
	return &CodexManagedDeviceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexManagedDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexManagedDeviceCreateBulk) OnConflictColumns(columns ...string) *CodexManagedDeviceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexManagedDeviceUpsertBulk{
		create: _c,
	}
}

// CodexManagedDeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexManagedDevice nodes.
type CodexManagedDeviceUpsertBulk struct {
	create *CodexManagedDeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexManagedDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexManagedDeviceUpsertBulk) UpdateNewValues() *CodexManagedDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexmanageddevice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexManagedDevice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexManagedDeviceUpsertBulk) Ignore() *CodexManagedDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexManagedDeviceUpsertBulk) DoNothing() *CodexManagedDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexManagedDeviceCreateBulk.OnConflict
// documentation for more info.
func (u *CodexManagedDeviceUpsertBulk) Update(set func(*CodexManagedDeviceUpsert)) *CodexManagedDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexManagedDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexManagedDeviceUpsertBulk) SetUpdatedAt(v time.Time) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateUpdatedAt() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CodexManagedDeviceUpsertBulk) SetUserID(v int64) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateUserID() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *CodexManagedDeviceUpsertBulk) SetAPIKeyID(v int64) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateAPIKeyID() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetName sets the "name" field.
func (u *CodexManagedDeviceUpsertBulk) SetName(v string) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateName() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *CodexManagedDeviceUpsertBulk) SetPlatform(v string) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdatePlatform() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdatePlatform()
	})
}

// SetArch sets the "arch" field.
func (u *CodexManagedDeviceUpsertBulk) SetArch(v string) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetArch(v)
	})
}

// UpdateArch sets the "arch" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateArch() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateArch()
	})
}

// SetManagerVersion sets the "manager_version" field.
func (u *CodexManagedDeviceUpsertBulk) SetManagerVersion(v string) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetManagerVersion(v)
	})
}

// UpdateManagerVersion sets the "manager_version" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateManagerVersion() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateManagerVersion()
	})
}

// SetStatus sets the "status" field.
func (u *CodexManagedDeviceUpsertBulk) SetStatus(v codexmanageddevice.Status) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateStatus() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *CodexManagedDeviceUpsertBulk) SetLastSeenAt(v time.Time) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateLastSeenAt() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *CodexManagedDeviceUpsertBulk) ClearLastSeenAt() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CodexManagedDeviceUpsertBulk) SetRevokedAt(v time.Time) *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CodexManagedDeviceUpsertBulk) UpdateRevokedAt() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CodexManagedDeviceUpsertBulk) ClearRevokedAt() *CodexManagedDeviceUpsertBulk {
	return u.Update(func(s *CodexManagedDeviceUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *CodexManagedDeviceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexManagedDeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexManagedDeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexManagedDeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
