// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexdeviceauditlog"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexDeviceAuditLogCreate is the builder for creating a CodexDeviceAuditLog entity.
type CodexDeviceAuditLogCreate struct {
	config
	mutation *CodexDeviceAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeviceID sets the "device_id" field.
func (_c *CodexDeviceAuditLogCreate) SetDeviceID(v int64) *CodexDeviceAuditLogCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CodexDeviceAuditLogCreate) SetUserID(v int64) *CodexDeviceAuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEvent sets the "event" field.
func (_c *CodexDeviceAuditLogCreate) SetEvent(v string) *CodexDeviceAuditLogCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *CodexDeviceAuditLogCreate) SetIP(v string) *CodexDeviceAuditLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *CodexDeviceAuditLogCreate) SetNillableIP(v *string) *CodexDeviceAuditLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *CodexDeviceAuditLogCreate) SetUserAgent(v string) *CodexDeviceAuditLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *CodexDeviceAuditLogCreate) SetNillableUserAgent(v *string) *CodexDeviceAuditLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *CodexDeviceAuditLogCreate) SetMetadata(v map[string]interface{}) *CodexDeviceAuditLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexDeviceAuditLogCreate) SetCreatedAt(v time.Time) *CodexDeviceAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexDeviceAuditLogCreate) SetNillableCreatedAt(v *time.Time) *CodexDeviceAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CodexDeviceAuditLogCreate) SetUser(v *User) *CodexDeviceAuditLogCreate {
	return _c.SetUserID(v.ID)
}

// SetDevice sets the "device" edge to the CodexManagedDevice entity.
func (_c *CodexDeviceAuditLogCreate) SetDevice(v *CodexManagedDevice) *CodexDeviceAuditLogCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the CodexDeviceAuditLogMutation object of the builder.
func (_c *CodexDeviceAuditLogCreate) Mutation() *CodexDeviceAuditLogMutation {
	return _c.mutation
}

// Save creates the CodexDeviceAuditLog in the database.
func (_c *CodexDeviceAuditLogCreate) Save(ctx context.Context) (*CodexDeviceAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexDeviceAuditLogCreate) SaveX(ctx context.Context) *CodexDeviceAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexDeviceAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexDeviceAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexDeviceAuditLogCreate) defaults() {
	if _, ok := _c.mutation.IP(); !ok {
		v := codexdeviceauditlog.DefaultIP
		_c.mutation.SetIP(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := codexdeviceauditlog.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := codexdeviceauditlog.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexdeviceauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexDeviceAuditLogCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.device_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.user_id"`)}
	}
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.event"`)}
	}
	if v, ok := _c.mutation.Event(); ok {
		if err := codexdeviceauditlog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceAuditLog.event": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := codexdeviceauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "CodexDeviceAuditLog.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.user_agent"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexDeviceAuditLog.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CodexDeviceAuditLog.user"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "CodexDeviceAuditLog.device"`)}
	}
	return nil
}

func (_c *CodexDeviceAuditLogCreate) sqlSave(ctx context.Context) (*CodexDeviceAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexDeviceAuditLogCreate) createSpec() (*CodexDeviceAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexDeviceAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexdeviceauditlog.Table, sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(codexdeviceauditlog.FieldEvent, field.TypeString, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(codexdeviceauditlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(codexdeviceauditlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(codexdeviceauditlog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexdeviceauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexdeviceauditlog.UserTable,
			Columns: []string{codexdeviceauditlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   codexdeviceauditlog.DeviceTable,
			Columns: []string{codexdeviceauditlog.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexDeviceAuditLog.Create().
//		SetDeviceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexDeviceAuditLogUpsert) {
//			SetDeviceID(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexDeviceAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *CodexDeviceAuditLogUpsertOne {
	_c.conflict = opts
	return &CodexDeviceAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexDeviceAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexDeviceAuditLogCreate) OnConflictColumns(columns ...string) *CodexDeviceAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexDeviceAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// CodexDeviceAuditLogUpsertOne is the builder for "upsert"-ing
	//  one CodexDeviceAuditLog node.
	CodexDeviceAuditLogUpsertOne struct {
		create *CodexDeviceAuditLogCreate
	}

	// CodexDeviceAuditLogUpsert is the "OnConflict" setter.
	CodexDeviceAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeviceID sets the "device_id" field.
func (u *CodexDeviceAuditLogUpsert) SetDeviceID(v int64) *CodexDeviceAuditLogUpsert {
	u.Set(codexdeviceauditlog.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsert) UpdateDeviceID() *CodexDeviceAuditLogUpsert {
	u.SetExcluded(codexdeviceauditlog.FieldDeviceID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CodexDeviceAuditLogUpsert) SetUserID(v int64) *CodexDeviceAuditLogUpsert {
	u.Set(codexdeviceauditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsert) UpdateUserID() *CodexDeviceAuditLogUpsert {
	u.SetExcluded(codexdeviceauditlog.FieldUserID)
	return u
}

// SetEvent sets the "event" field.
func (u *CodexDeviceAuditLogUpsert) SetEvent(v string) *CodexDeviceAuditLogUpsert {
	u.Set(codexdeviceauditlog.FieldEvent, v)
	return u
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsert) UpdateEvent() *CodexDeviceAuditLogUpsert {
	u.SetExcluded(codexdeviceauditlog.FieldEvent)
	return u
}

// SetIP sets the "ip" field.
func (u *CodexDeviceAuditLogUpsert) SetIP(v string) *CodexDeviceAuditLogUpsert {
	u.Set(codexdeviceauditlog.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsert) UpdateIP() *CodexDeviceAuditLogUpsert {
	u.SetExcluded(codexdeviceauditlog.FieldIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *CodexDeviceAuditLogUpsert) SetUserAgent(v string) *CodexDeviceAuditLogUpsert {
	u.Set(codexdeviceauditlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsert) UpdateUserAgent() *CodexDeviceAuditLogUpsert {
	u.SetExcluded(codexdeviceauditlog.FieldUserAgent)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *CodexDeviceAuditLogUpsert) SetMetadata(v map[string]interface{}) *CodexDeviceAuditLogUpsert {
	u.Set(codexdeviceauditlog.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsert) UpdateMetadata() *CodexDeviceAuditLogUpsert {
	u.SetExcluded(codexdeviceauditlog.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexDeviceAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexDeviceAuditLogUpsertOne) UpdateNewValues() *CodexDeviceAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexdeviceauditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexDeviceAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexDeviceAuditLogUpsertOne) Ignore() *CodexDeviceAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexDeviceAuditLogUpsertOne) DoNothing() *CodexDeviceAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexDeviceAuditLogCreate.OnConflict
// documentation for more info.
func (u *CodexDeviceAuditLogUpsertOne) Update(set func(*CodexDeviceAuditLogUpsert)) *CodexDeviceAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexDeviceAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *CodexDeviceAuditLogUpsertOne) SetDeviceID(v int64) *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertOne) UpdateDeviceID() *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateDeviceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CodexDeviceAuditLogUpsertOne) SetUserID(v int64) *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertOne) UpdateUserID() *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// SetEvent sets the "event" field.
func (u *CodexDeviceAuditLogUpsertOne) SetEvent(v string) *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertOne) UpdateEvent() *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateEvent()
	})
}

// SetIP sets the "ip" field.
func (u *CodexDeviceAuditLogUpsertOne) SetIP(v string) *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertOne) UpdateIP() *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *CodexDeviceAuditLogUpsertOne) SetUserAgent(v string) *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertOne) UpdateUserAgent() *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CodexDeviceAuditLogUpsertOne) SetMetadata(v map[string]interface{}) *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertOne) UpdateMetadata() *CodexDeviceAuditLogUpsertOne {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *CodexDeviceAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexDeviceAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexDeviceAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexDeviceAuditLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexDeviceAuditLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexDeviceAuditLogCreateBulk is the builder for creating many CodexDeviceAuditLog entities in bulk.
type CodexDeviceAuditLogCreateBulk struct {
	config
	err      error
	builders []*CodexDeviceAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexDeviceAuditLog entities in the database.
func (_c *CodexDeviceAuditLogCreateBulk) Save(ctx context.Context) ([]*CodexDeviceAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexDeviceAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexDeviceAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexDeviceAuditLogCreateBulk) SaveX(ctx context.Context) []*CodexDeviceAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexDeviceAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexDeviceAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexDeviceAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexDeviceAuditLogUpsert) {
//			SetDeviceID(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexDeviceAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexDeviceAuditLogUpsertBulk {
	_c.conflict = opts
	return &CodexDeviceAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexDeviceAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexDeviceAuditLogCreateBulk) OnConflictColumns(columns ...string) *CodexDeviceAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexDeviceAuditLogUpsertBulk{
		create: _c,
	}
}

// CodexDeviceAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexDeviceAuditLog nodes.
type CodexDeviceAuditLogUpsertBulk struct {
	create *CodexDeviceAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexDeviceAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexDeviceAuditLogUpsertBulk) UpdateNewValues() *CodexDeviceAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexdeviceauditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexDeviceAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexDeviceAuditLogUpsertBulk) Ignore() *CodexDeviceAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexDeviceAuditLogUpsertBulk) DoNothing() *CodexDeviceAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexDeviceAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *CodexDeviceAuditLogUpsertBulk) Update(set func(*CodexDeviceAuditLogUpsert)) *CodexDeviceAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexDeviceAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *CodexDeviceAuditLogUpsertBulk) SetDeviceID(v int64) *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertBulk) UpdateDeviceID() *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateDeviceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CodexDeviceAuditLogUpsertBulk) SetUserID(v int64) *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertBulk) UpdateUserID() *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// SetEvent sets the "event" field.
func (u *CodexDeviceAuditLogUpsertBulk) SetEvent(v string) *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertBulk) UpdateEvent() *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateEvent()
	})
}

// SetIP sets the "ip" field.
func (u *CodexDeviceAuditLogUpsertBulk) SetIP(v string) *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertBulk) UpdateIP() *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *CodexDeviceAuditLogUpsertBulk) SetUserAgent(v string) *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertBulk) UpdateUserAgent() *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CodexDeviceAuditLogUpsertBulk) SetMetadata(v map[string]interface{}) *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CodexDeviceAuditLogUpsertBulk) UpdateMetadata() *CodexDeviceAuditLogUpsertBulk {
	return u.Update(func(s *CodexDeviceAuditLogUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *CodexDeviceAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexDeviceAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexDeviceAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexDeviceAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
