// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/codexsetupgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexSetupGrantUpdate is the builder for updating CodexSetupGrant entities.
type CodexSetupGrantUpdate struct {
	config
	hooks    []Hook
	mutation *CodexSetupGrantMutation
}

// Where appends a list predicates to the CodexSetupGrantUpdate builder.
func (_u *CodexSetupGrantUpdate) Where(ps ...predicate.CodexSetupGrant) *CodexSetupGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *CodexSetupGrantUpdate) SetCodeHash(v string) *CodexSetupGrantUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableCodeHash(v *string) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CodexSetupGrantUpdate) SetUserID(v int64) *CodexSetupGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableUserID(v *int64) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *CodexSetupGrantUpdate) SetAPIKeyID(v int64) *CodexSetupGrantUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableAPIKeyID(v *int64) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *CodexSetupGrantUpdate) SetMode(v string) *CodexSetupGrantUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableMode(v *string) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetServerOrigin sets the "server_origin" field.
func (_u *CodexSetupGrantUpdate) SetServerOrigin(v string) *CodexSetupGrantUpdate {
	_u.mutation.SetServerOrigin(v)
	return _u
}

// SetNillableServerOrigin sets the "server_origin" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableServerOrigin(v *string) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetServerOrigin(*v)
	}
	return _u
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (_u *CodexSetupGrantUpdate) SetGatewayOrigin(v string) *CodexSetupGrantUpdate {
	_u.mutation.SetGatewayOrigin(v)
	return _u
}

// SetNillableGatewayOrigin sets the "gateway_origin" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableGatewayOrigin(v *string) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetGatewayOrigin(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexSetupGrantUpdate) SetExpiresAt(v time.Time) *CodexSetupGrantUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableExpiresAt(v *time.Time) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *CodexSetupGrantUpdate) SetConsumedAt(v time.Time) *CodexSetupGrantUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *CodexSetupGrantUpdate) SetNillableConsumedAt(v *time.Time) *CodexSetupGrantUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *CodexSetupGrantUpdate) ClearConsumedAt() *CodexSetupGrantUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CodexSetupGrantUpdate) SetUser(v *User) *CodexSetupGrantUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *CodexSetupGrantUpdate) SetAPIKey(v *APIKey) *CodexSetupGrantUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the CodexSetupGrantMutation object of the builder.
func (_u *CodexSetupGrantUpdate) Mutation() *CodexSetupGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CodexSetupGrantUpdate) ClearUser() *CodexSetupGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *CodexSetupGrantUpdate) ClearAPIKey() *CodexSetupGrantUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexSetupGrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexSetupGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexSetupGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexSetupGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexSetupGrantUpdate) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := codexsetupgrant.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := codexsetupgrant.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerOrigin(); ok {
		if err := codexsetupgrant.ServerOriginValidator(v); err != nil {
			return &ValidationError{Name: "server_origin", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.server_origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayOrigin(); ok {
		if err := codexsetupgrant.GatewayOriginValidator(v); err != nil {
			return &ValidationError{Name: "gateway_origin", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.gateway_origin": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexSetupGrant.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexSetupGrant.api_key"`)
	}
	return nil
}

func (_u *CodexSetupGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexsetupgrant.Table, codexsetupgrant.Columns, sqlgraph.NewFieldSpec(codexsetupgrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(codexsetupgrant.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(codexsetupgrant.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerOrigin(); ok {
		_spec.SetField(codexsetupgrant.FieldServerOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayOrigin(); ok {
		_spec.SetField(codexsetupgrant.FieldGatewayOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexsetupgrant.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(codexsetupgrant.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(codexsetupgrant.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.UserTable,
			Columns: []string{codexsetupgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.UserTable,
			Columns: []string{codexsetupgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.APIKeyTable,
			Columns: []string{codexsetupgrant.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.APIKeyTable,
			Columns: []string{codexsetupgrant.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexsetupgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexSetupGrantUpdateOne is the builder for updating a single CodexSetupGrant entity.
type CodexSetupGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexSetupGrantMutation
}

// SetCodeHash sets the "code_hash" field.
func (_u *CodexSetupGrantUpdateOne) SetCodeHash(v string) *CodexSetupGrantUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableCodeHash(v *string) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CodexSetupGrantUpdateOne) SetUserID(v int64) *CodexSetupGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableUserID(v *int64) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *CodexSetupGrantUpdateOne) SetAPIKeyID(v int64) *CodexSetupGrantUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableAPIKeyID(v *int64) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *CodexSetupGrantUpdateOne) SetMode(v string) *CodexSetupGrantUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableMode(v *string) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetServerOrigin sets the "server_origin" field.
func (_u *CodexSetupGrantUpdateOne) SetServerOrigin(v string) *CodexSetupGrantUpdateOne {
	_u.mutation.SetServerOrigin(v)
	return _u
}

// SetNillableServerOrigin sets the "server_origin" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableServerOrigin(v *string) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetServerOrigin(*v)
	}
	return _u
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (_u *CodexSetupGrantUpdateOne) SetGatewayOrigin(v string) *CodexSetupGrantUpdateOne {
	_u.mutation.SetGatewayOrigin(v)
	return _u
}

// SetNillableGatewayOrigin sets the "gateway_origin" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableGatewayOrigin(v *string) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetGatewayOrigin(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexSetupGrantUpdateOne) SetExpiresAt(v time.Time) *CodexSetupGrantUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableExpiresAt(v *time.Time) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *CodexSetupGrantUpdateOne) SetConsumedAt(v time.Time) *CodexSetupGrantUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *CodexSetupGrantUpdateOne) SetNillableConsumedAt(v *time.Time) *CodexSetupGrantUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *CodexSetupGrantUpdateOne) ClearConsumedAt() *CodexSetupGrantUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CodexSetupGrantUpdateOne) SetUser(v *User) *CodexSetupGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *CodexSetupGrantUpdateOne) SetAPIKey(v *APIKey) *CodexSetupGrantUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the CodexSetupGrantMutation object of the builder.
func (_u *CodexSetupGrantUpdateOne) Mutation() *CodexSetupGrantMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CodexSetupGrantUpdateOne) ClearUser() *CodexSetupGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *CodexSetupGrantUpdateOne) ClearAPIKey() *CodexSetupGrantUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the CodexSetupGrantUpdate builder.
func (_u *CodexSetupGrantUpdateOne) Where(ps ...predicate.CodexSetupGrant) *CodexSetupGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexSetupGrantUpdateOne) Select(field string, fields ...string) *CodexSetupGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexSetupGrant entity.
func (_u *CodexSetupGrantUpdateOne) Save(ctx context.Context) (*CodexSetupGrant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexSetupGrantUpdateOne) SaveX(ctx context.Context) *CodexSetupGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexSetupGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexSetupGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexSetupGrantUpdateOne) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := codexsetupgrant.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := codexsetupgrant.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServerOrigin(); ok {
		if err := codexsetupgrant.ServerOriginValidator(v); err != nil {
			return &ValidationError{Name: "server_origin", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.server_origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayOrigin(); ok {
		if err := codexsetupgrant.GatewayOriginValidator(v); err != nil {
			return &ValidationError{Name: "gateway_origin", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.gateway_origin": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexSetupGrant.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexSetupGrant.api_key"`)
	}
	return nil
}

func (_u *CodexSetupGrantUpdateOne) sqlSave(ctx context.Context) (_node *CodexSetupGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexsetupgrant.Table, codexsetupgrant.Columns, sqlgraph.NewFieldSpec(codexsetupgrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexSetupGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexsetupgrant.FieldID)
		for _, f := range fields {
			if !codexsetupgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexsetupgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(codexsetupgrant.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(codexsetupgrant.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerOrigin(); ok {
		_spec.SetField(codexsetupgrant.FieldServerOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayOrigin(); ok {
		_spec.SetField(codexsetupgrant.FieldGatewayOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexsetupgrant.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(codexsetupgrant.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(codexsetupgrant.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.UserTable,
			Columns: []string{codexsetupgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.UserTable,
			Columns: []string{codexsetupgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.APIKeyTable,
			Columns: []string{codexsetupgrant.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.APIKeyTable,
			Columns: []string{codexsetupgrant.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodexSetupGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexsetupgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
