// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/codexdeviceauditlog"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexDeviceAuditLog is the model entity for the CodexDeviceAuditLog schema.
type CodexDeviceAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID int64 `json:"device_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Event holds the value of the "event" field.
	Event string `json:"event,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CodexDeviceAuditLogQuery when eager-loading is set.
	Edges        CodexDeviceAuditLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CodexDeviceAuditLogEdges holds the relations/edges for other nodes in the graph.
type CodexDeviceAuditLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Device holds the value of the device edge.
	Device *CodexManagedDevice `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CodexDeviceAuditLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CodexDeviceAuditLogEdges) DeviceOrErr() (*CodexManagedDevice, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: codexmanageddevice.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexDeviceAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexdeviceauditlog.FieldMetadata:
			values[i] = new([]byte)
		case codexdeviceauditlog.FieldID, codexdeviceauditlog.FieldDeviceID, codexdeviceauditlog.FieldUserID:
			values[i] = new(sql.NullInt64)
		case codexdeviceauditlog.FieldEvent, codexdeviceauditlog.FieldIP, codexdeviceauditlog.FieldUserAgent:
			values[i] = new(sql.NullString)
		case codexdeviceauditlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexDeviceAuditLog fields.
func (_m *CodexDeviceAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexdeviceauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case codexdeviceauditlog.FieldDeviceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.Int64
			}
		case codexdeviceauditlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case codexdeviceauditlog.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				_m.Event = value.String
			}
		case codexdeviceauditlog.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case codexdeviceauditlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case codexdeviceauditlog.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case codexdeviceauditlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexDeviceAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *CodexDeviceAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CodexDeviceAuditLog entity.
func (_m *CodexDeviceAuditLog) QueryUser() *UserQuery {
	return NewCodexDeviceAuditLogClient(_m.config).QueryUser(_m)
}

// QueryDevice queries the "device" edge of the CodexDeviceAuditLog entity.
func (_m *CodexDeviceAuditLog) QueryDevice() *CodexManagedDeviceQuery {
	return NewCodexDeviceAuditLogClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this CodexDeviceAuditLog.
// Note that you need to call CodexDeviceAuditLog.Unwrap() before calling this method if this CodexDeviceAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexDeviceAuditLog) Update() *CodexDeviceAuditLogUpdateOne {
	return NewCodexDeviceAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexDeviceAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexDeviceAuditLog) Unwrap() *CodexDeviceAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexDeviceAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexDeviceAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("CodexDeviceAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(_m.Event)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CodexDeviceAuditLogs is a parsable slice of CodexDeviceAuditLog.
type CodexDeviceAuditLogs []*CodexDeviceAuditLog
