// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/codexsetupgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexSetupGrantCreate is the builder for creating a CodexSetupGrant entity.
type CodexSetupGrantCreate struct {
	config
	mutation *CodexSetupGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCodeHash sets the "code_hash" field.
func (_c *CodexSetupGrantCreate) SetCodeHash(v string) *CodexSetupGrantCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CodexSetupGrantCreate) SetUserID(v int64) *CodexSetupGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *CodexSetupGrantCreate) SetAPIKeyID(v int64) *CodexSetupGrantCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *CodexSetupGrantCreate) SetMode(v string) *CodexSetupGrantCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetServerOrigin sets the "server_origin" field.
func (_c *CodexSetupGrantCreate) SetServerOrigin(v string) *CodexSetupGrantCreate {
	_c.mutation.SetServerOrigin(v)
	return _c
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (_c *CodexSetupGrantCreate) SetGatewayOrigin(v string) *CodexSetupGrantCreate {
	_c.mutation.SetGatewayOrigin(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CodexSetupGrantCreate) SetExpiresAt(v time.Time) *CodexSetupGrantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *CodexSetupGrantCreate) SetConsumedAt(v time.Time) *CodexSetupGrantCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *CodexSetupGrantCreate) SetNillableConsumedAt(v *time.Time) *CodexSetupGrantCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexSetupGrantCreate) SetCreatedAt(v time.Time) *CodexSetupGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexSetupGrantCreate) SetNillableCreatedAt(v *time.Time) *CodexSetupGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CodexSetupGrantCreate) SetUser(v *User) *CodexSetupGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *CodexSetupGrantCreate) SetAPIKey(v *APIKey) *CodexSetupGrantCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the CodexSetupGrantMutation object of the builder.
func (_c *CodexSetupGrantCreate) Mutation() *CodexSetupGrantMutation {
	return _c.mutation
}

// Save creates the CodexSetupGrant in the database.
func (_c *CodexSetupGrantCreate) Save(ctx context.Context) (*CodexSetupGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexSetupGrantCreate) SaveX(ctx context.Context) *CodexSetupGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexSetupGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexSetupGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexSetupGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexsetupgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexSetupGrantCreate) check() error {
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "CodexSetupGrant.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := codexsetupgrant.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CodexSetupGrant.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "CodexSetupGrant.api_key_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "CodexSetupGrant.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := codexsetupgrant.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServerOrigin(); !ok {
		return &ValidationError{Name: "server_origin", err: errors.New(`ent: missing required field "CodexSetupGrant.server_origin"`)}
	}
	if v, ok := _c.mutation.ServerOrigin(); ok {
		if err := codexsetupgrant.ServerOriginValidator(v); err != nil {
			return &ValidationError{Name: "server_origin", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.server_origin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GatewayOrigin(); !ok {
		return &ValidationError{Name: "gateway_origin", err: errors.New(`ent: missing required field "CodexSetupGrant.gateway_origin"`)}
	}
	if v, ok := _c.mutation.GatewayOrigin(); ok {
		if err := codexsetupgrant.GatewayOriginValidator(v); err != nil {
			return &ValidationError{Name: "gateway_origin", err: fmt.Errorf(`ent: validator failed for field "CodexSetupGrant.gateway_origin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CodexSetupGrant.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexSetupGrant.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CodexSetupGrant.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "CodexSetupGrant.api_key"`)}
	}
	return nil
}

func (_c *CodexSetupGrantCreate) sqlSave(ctx context.Context) (*CodexSetupGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexSetupGrantCreate) createSpec() (*CodexSetupGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexSetupGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexsetupgrant.Table, sqlgraph.NewFieldSpec(codexsetupgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(codexsetupgrant.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(codexsetupgrant.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.ServerOrigin(); ok {
		_spec.SetField(codexsetupgrant.FieldServerOrigin, field.TypeString, value)
		_node.ServerOrigin = value
	}
	if value, ok := _c.mutation.GatewayOrigin(); ok {
		_spec.SetField(codexsetupgrant.FieldGatewayOrigin, field.TypeString, value)
		_node.GatewayOrigin = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(codexsetupgrant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(codexsetupgrant.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexsetupgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.UserTable,
			Columns: []string{codexsetupgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexsetupgrant.APIKeyTable,
			Columns: []string{codexsetupgrant.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexSetupGrant.Create().
//		SetCodeHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexSetupGrantUpsert) {
//			SetCodeHash(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexSetupGrantCreate) OnConflict(opts ...sql.ConflictOption) *CodexSetupGrantUpsertOne {
	_c.conflict = opts
	return &CodexSetupGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexSetupGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexSetupGrantCreate) OnConflictColumns(columns ...string) *CodexSetupGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexSetupGrantUpsertOne{
		create: _c,
	}
}

type (
	// CodexSetupGrantUpsertOne is the builder for "upsert"-ing
	//  one CodexSetupGrant node.
	CodexSetupGrantUpsertOne struct {
		create *CodexSetupGrantCreate
	}

	// CodexSetupGrantUpsert is the "OnConflict" setter.
	CodexSetupGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetCodeHash sets the "code_hash" field.
func (u *CodexSetupGrantUpsert) SetCodeHash(v string) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldCodeHash, v)
	return u
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateCodeHash() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldCodeHash)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CodexSetupGrantUpsert) SetUserID(v int64) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateUserID() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *CodexSetupGrantUpsert) SetAPIKeyID(v int64) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateAPIKeyID() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldAPIKeyID)
	return u
}

// SetMode sets the "mode" field.
func (u *CodexSetupGrantUpsert) SetMode(v string) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateMode() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldMode)
	return u
}

// SetServerOrigin sets the "server_origin" field.
func (u *CodexSetupGrantUpsert) SetServerOrigin(v string) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldServerOrigin, v)
	return u
}

// UpdateServerOrigin sets the "server_origin" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateServerOrigin() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldServerOrigin)
	return u
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (u *CodexSetupGrantUpsert) SetGatewayOrigin(v string) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldGatewayOrigin, v)
	return u
}

// UpdateGatewayOrigin sets the "gateway_origin" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateGatewayOrigin() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldGatewayOrigin)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexSetupGrantUpsert) SetExpiresAt(v time.Time) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateExpiresAt() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CodexSetupGrantUpsert) SetConsumedAt(v time.Time) *CodexSetupGrantUpsert {
	u.Set(codexsetupgrant.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CodexSetupGrantUpsert) UpdateConsumedAt() *CodexSetupGrantUpsert {
	u.SetExcluded(codexsetupgrant.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CodexSetupGrantUpsert) ClearConsumedAt() *CodexSetupGrantUpsert {
	u.SetNull(codexsetupgrant.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexSetupGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexSetupGrantUpsertOne) UpdateNewValues() *CodexSetupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexsetupgrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexSetupGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexSetupGrantUpsertOne) Ignore() *CodexSetupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexSetupGrantUpsertOne) DoNothing() *CodexSetupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexSetupGrantCreate.OnConflict
// documentation for more info.
func (u *CodexSetupGrantUpsertOne) Update(set func(*CodexSetupGrantUpsert)) *CodexSetupGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexSetupGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *CodexSetupGrantUpsertOne) SetCodeHash(v string) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateCodeHash() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateCodeHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *CodexSetupGrantUpsertOne) SetUserID(v int64) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateUserID() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *CodexSetupGrantUpsertOne) SetAPIKeyID(v int64) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateAPIKeyID() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetMode sets the "mode" field.
func (u *CodexSetupGrantUpsertOne) SetMode(v string) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateMode() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateMode()
	})
}

// SetServerOrigin sets the "server_origin" field.
func (u *CodexSetupGrantUpsertOne) SetServerOrigin(v string) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetServerOrigin(v)
	})
}

// UpdateServerOrigin sets the "server_origin" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateServerOrigin() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateServerOrigin()
	})
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (u *CodexSetupGrantUpsertOne) SetGatewayOrigin(v string) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetGatewayOrigin(v)
	})
}

// UpdateGatewayOrigin sets the "gateway_origin" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateGatewayOrigin() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateGatewayOrigin()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexSetupGrantUpsertOne) SetExpiresAt(v time.Time) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateExpiresAt() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CodexSetupGrantUpsertOne) SetConsumedAt(v time.Time) *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertOne) UpdateConsumedAt() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CodexSetupGrantUpsertOne) ClearConsumedAt() *CodexSetupGrantUpsertOne {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *CodexSetupGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexSetupGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexSetupGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexSetupGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexSetupGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexSetupGrantCreateBulk is the builder for creating many CodexSetupGrant entities in bulk.
type CodexSetupGrantCreateBulk struct {
	config
	err      error
	builders []*CodexSetupGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexSetupGrant entities in the database.
func (_c *CodexSetupGrantCreateBulk) Save(ctx context.Context) ([]*CodexSetupGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexSetupGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexSetupGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexSetupGrantCreateBulk) SaveX(ctx context.Context) []*CodexSetupGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexSetupGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexSetupGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexSetupGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexSetupGrantUpsert) {
//			SetCodeHash(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexSetupGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexSetupGrantUpsertBulk {
	_c.conflict = opts
	return &CodexSetupGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexSetupGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexSetupGrantCreateBulk) OnConflictColumns(columns ...string) *CodexSetupGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexSetupGrantUpsertBulk{
		create: _c,
	}
}

// CodexSetupGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexSetupGrant nodes.
type CodexSetupGrantUpsertBulk struct {
	create *CodexSetupGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexSetupGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexSetupGrantUpsertBulk) UpdateNewValues() *CodexSetupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexsetupgrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexSetupGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexSetupGrantUpsertBulk) Ignore() *CodexSetupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexSetupGrantUpsertBulk) DoNothing() *CodexSetupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexSetupGrantCreateBulk.OnConflict
// documentation for more info.
func (u *CodexSetupGrantUpsertBulk) Update(set func(*CodexSetupGrantUpsert)) *CodexSetupGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexSetupGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *CodexSetupGrantUpsertBulk) SetCodeHash(v string) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateCodeHash() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateCodeHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *CodexSetupGrantUpsertBulk) SetUserID(v int64) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateUserID() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *CodexSetupGrantUpsertBulk) SetAPIKeyID(v int64) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateAPIKeyID() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetMode sets the "mode" field.
func (u *CodexSetupGrantUpsertBulk) SetMode(v string) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateMode() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateMode()
	})
}

// SetServerOrigin sets the "server_origin" field.
func (u *CodexSetupGrantUpsertBulk) SetServerOrigin(v string) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetServerOrigin(v)
	})
}

// UpdateServerOrigin sets the "server_origin" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateServerOrigin() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateServerOrigin()
	})
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (u *CodexSetupGrantUpsertBulk) SetGatewayOrigin(v string) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetGatewayOrigin(v)
	})
}

// UpdateGatewayOrigin sets the "gateway_origin" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateGatewayOrigin() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateGatewayOrigin()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexSetupGrantUpsertBulk) SetExpiresAt(v time.Time) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateExpiresAt() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *CodexSetupGrantUpsertBulk) SetConsumedAt(v time.Time) *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *CodexSetupGrantUpsertBulk) UpdateConsumedAt() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *CodexSetupGrantUpsertBulk) ClearConsumedAt() *CodexSetupGrantUpsertBulk {
	return u.Update(func(s *CodexSetupGrantUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *CodexSetupGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexSetupGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexSetupGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexSetupGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
