// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/codexdeviceauditlog"
	"github.com/Wei-Shaw/sub2api/ent/codexdevicetoken"
	"github.com/Wei-Shaw/sub2api/ent/codexmanageddevice"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CodexManagedDeviceUpdate is the builder for updating CodexManagedDevice entities.
type CodexManagedDeviceUpdate struct {
	config
	hooks    []Hook
	mutation *CodexManagedDeviceMutation
}

// Where appends a list predicates to the CodexManagedDeviceUpdate builder.
func (_u *CodexManagedDeviceUpdate) Where(ps ...predicate.CodexManagedDevice) *CodexManagedDeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexManagedDeviceUpdate) SetUpdatedAt(v time.Time) *CodexManagedDeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CodexManagedDeviceUpdate) SetUserID(v int64) *CodexManagedDeviceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableUserID(v *int64) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *CodexManagedDeviceUpdate) SetAPIKeyID(v int64) *CodexManagedDeviceUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableAPIKeyID(v *int64) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CodexManagedDeviceUpdate) SetName(v string) *CodexManagedDeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableName(v *string) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CodexManagedDeviceUpdate) SetPlatform(v string) *CodexManagedDeviceUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillablePlatform(v *string) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetArch sets the "arch" field.
func (_u *CodexManagedDeviceUpdate) SetArch(v string) *CodexManagedDeviceUpdate {
	_u.mutation.SetArch(v)
	return _u
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableArch(v *string) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetArch(*v)
	}
	return _u
}

// SetManagerVersion sets the "manager_version" field.
func (_u *CodexManagedDeviceUpdate) SetManagerVersion(v string) *CodexManagedDeviceUpdate {
	_u.mutation.SetManagerVersion(v)
	return _u
}

// SetNillableManagerVersion sets the "manager_version" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableManagerVersion(v *string) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetManagerVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CodexManagedDeviceUpdate) SetStatus(v codexmanageddevice.Status) *CodexManagedDeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableStatus(v *codexmanageddevice.Status) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *CodexManagedDeviceUpdate) SetLastSeenAt(v time.Time) *CodexManagedDeviceUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableLastSeenAt(v *time.Time) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *CodexManagedDeviceUpdate) ClearLastSeenAt() *CodexManagedDeviceUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *CodexManagedDeviceUpdate) SetRevokedAt(v time.Time) *CodexManagedDeviceUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdate) SetNillableRevokedAt(v *time.Time) *CodexManagedDeviceUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *CodexManagedDeviceUpdate) ClearRevokedAt() *CodexManagedDeviceUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CodexManagedDeviceUpdate) SetUser(v *User) *CodexManagedDeviceUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *CodexManagedDeviceUpdate) SetAPIKey(v *APIKey) *CodexManagedDeviceUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// AddTokenIDs adds the "tokens" edge to the CodexDeviceToken entity by IDs.
func (_u *CodexManagedDeviceUpdate) AddTokenIDs(ids ...int64) *CodexManagedDeviceUpdate {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the CodexDeviceToken entity.
func (_u *CodexManagedDeviceUpdate) AddTokens(v ...*CodexDeviceToken) *CodexManagedDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the CodexDeviceAuditLog entity by IDs.
func (_u *CodexManagedDeviceUpdate) AddAuditLogIDs(ids ...int64) *CodexManagedDeviceUpdate {
	_u.mutation.AddAuditLogIDs(ids...)
	return _u
}

// AddAuditLogs adds the "audit_logs" edges to the CodexDeviceAuditLog entity.
func (_u *CodexManagedDeviceUpdate) AddAuditLogs(v ...*CodexDeviceAuditLog) *CodexManagedDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditLogIDs(ids...)
}

// Mutation returns the CodexManagedDeviceMutation object of the builder.
func (_u *CodexManagedDeviceUpdate) Mutation() *CodexManagedDeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CodexManagedDeviceUpdate) ClearUser() *CodexManagedDeviceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *CodexManagedDeviceUpdate) ClearAPIKey() *CodexManagedDeviceUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearTokens clears all "tokens" edges to the CodexDeviceToken entity.
func (_u *CodexManagedDeviceUpdate) ClearTokens() *CodexManagedDeviceUpdate {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to CodexDeviceToken entities by IDs.
func (_u *CodexManagedDeviceUpdate) RemoveTokenIDs(ids ...int64) *CodexManagedDeviceUpdate {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to CodexDeviceToken entities.
func (_u *CodexManagedDeviceUpdate) RemoveTokens(v ...*CodexDeviceToken) *CodexManagedDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// ClearAuditLogs clears all "audit_logs" edges to the CodexDeviceAuditLog entity.
func (_u *CodexManagedDeviceUpdate) ClearAuditLogs() *CodexManagedDeviceUpdate {
	_u.mutation.ClearAuditLogs()
	return _u
}

// RemoveAuditLogIDs removes the "audit_logs" edge to CodexDeviceAuditLog entities by IDs.
func (_u *CodexManagedDeviceUpdate) RemoveAuditLogIDs(ids ...int64) *CodexManagedDeviceUpdate {
	_u.mutation.RemoveAuditLogIDs(ids...)
	return _u
}

// RemoveAuditLogs removes "audit_logs" edges to CodexDeviceAuditLog entities.
func (_u *CodexManagedDeviceUpdate) RemoveAuditLogs(v ...*CodexDeviceAuditLog) *CodexManagedDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexManagedDeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexManagedDeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexManagedDeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexManagedDeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexManagedDeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexmanageddevice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexManagedDeviceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := codexmanageddevice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := codexmanageddevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Arch(); ok {
		if err := codexmanageddevice.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.arch": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagerVersion(); ok {
		if err := codexmanageddevice.ManagerVersionValidator(v); err != nil {
			return &ValidationError{Name: "manager_version", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.manager_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := codexmanageddevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexManagedDevice.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexManagedDevice.api_key"`)
	}
	return nil
}

func (_u *CodexManagedDeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexmanageddevice.Table, codexmanageddevice.Columns, sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codexmanageddevice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(codexmanageddevice.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Arch(); ok {
		_spec.SetField(codexmanageddevice.FieldArch, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagerVersion(); ok {
		_spec.SetField(codexmanageddevice.FieldManagerVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(codexmanageddevice.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(codexmanageddevice.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(codexmanageddevice.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(codexmanageddevice.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.UserTable,
			Columns: []string{codexmanageddevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.UserTable,
			Columns: []string{codexmanageddevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.APIKeyTable,
			Columns: []string{codexmanageddevice.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.APIKeyTable,
			Columns: []string{codexmanageddevice.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditLogsIDs(); len(nodes) > 0 && !_u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexmanageddevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexManagedDeviceUpdateOne is the builder for updating a single CodexManagedDevice entity.
type CodexManagedDeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexManagedDeviceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexManagedDeviceUpdateOne) SetUpdatedAt(v time.Time) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CodexManagedDeviceUpdateOne) SetUserID(v int64) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableUserID(v *int64) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *CodexManagedDeviceUpdateOne) SetAPIKeyID(v int64) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableAPIKeyID(v *int64) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CodexManagedDeviceUpdateOne) SetName(v string) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableName(v *string) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CodexManagedDeviceUpdateOne) SetPlatform(v string) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillablePlatform(v *string) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetArch sets the "arch" field.
func (_u *CodexManagedDeviceUpdateOne) SetArch(v string) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetArch(v)
	return _u
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableArch(v *string) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetArch(*v)
	}
	return _u
}

// SetManagerVersion sets the "manager_version" field.
func (_u *CodexManagedDeviceUpdateOne) SetManagerVersion(v string) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetManagerVersion(v)
	return _u
}

// SetNillableManagerVersion sets the "manager_version" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableManagerVersion(v *string) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetManagerVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CodexManagedDeviceUpdateOne) SetStatus(v codexmanageddevice.Status) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableStatus(v *codexmanageddevice.Status) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *CodexManagedDeviceUpdateOne) SetLastSeenAt(v time.Time) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableLastSeenAt(v *time.Time) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *CodexManagedDeviceUpdateOne) ClearLastSeenAt() *CodexManagedDeviceUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *CodexManagedDeviceUpdateOne) SetRevokedAt(v time.Time) *CodexManagedDeviceUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *CodexManagedDeviceUpdateOne) SetNillableRevokedAt(v *time.Time) *CodexManagedDeviceUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *CodexManagedDeviceUpdateOne) ClearRevokedAt() *CodexManagedDeviceUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CodexManagedDeviceUpdateOne) SetUser(v *User) *CodexManagedDeviceUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *CodexManagedDeviceUpdateOne) SetAPIKey(v *APIKey) *CodexManagedDeviceUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// AddTokenIDs adds the "tokens" edge to the CodexDeviceToken entity by IDs.
func (_u *CodexManagedDeviceUpdateOne) AddTokenIDs(ids ...int64) *CodexManagedDeviceUpdateOne {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the CodexDeviceToken entity.
func (_u *CodexManagedDeviceUpdateOne) AddTokens(v ...*CodexDeviceToken) *CodexManagedDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the CodexDeviceAuditLog entity by IDs.
func (_u *CodexManagedDeviceUpdateOne) AddAuditLogIDs(ids ...int64) *CodexManagedDeviceUpdateOne {
	_u.mutation.AddAuditLogIDs(ids...)
	return _u
}

// AddAuditLogs adds the "audit_logs" edges to the CodexDeviceAuditLog entity.
func (_u *CodexManagedDeviceUpdateOne) AddAuditLogs(v ...*CodexDeviceAuditLog) *CodexManagedDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuditLogIDs(ids...)
}

// Mutation returns the CodexManagedDeviceMutation object of the builder.
func (_u *CodexManagedDeviceUpdateOne) Mutation() *CodexManagedDeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CodexManagedDeviceUpdateOne) ClearUser() *CodexManagedDeviceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *CodexManagedDeviceUpdateOne) ClearAPIKey() *CodexManagedDeviceUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearTokens clears all "tokens" edges to the CodexDeviceToken entity.
func (_u *CodexManagedDeviceUpdateOne) ClearTokens() *CodexManagedDeviceUpdateOne {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to CodexDeviceToken entities by IDs.
func (_u *CodexManagedDeviceUpdateOne) RemoveTokenIDs(ids ...int64) *CodexManagedDeviceUpdateOne {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to CodexDeviceToken entities.
func (_u *CodexManagedDeviceUpdateOne) RemoveTokens(v ...*CodexDeviceToken) *CodexManagedDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// ClearAuditLogs clears all "audit_logs" edges to the CodexDeviceAuditLog entity.
func (_u *CodexManagedDeviceUpdateOne) ClearAuditLogs() *CodexManagedDeviceUpdateOne {
	_u.mutation.ClearAuditLogs()
	return _u
}

// RemoveAuditLogIDs removes the "audit_logs" edge to CodexDeviceAuditLog entities by IDs.
func (_u *CodexManagedDeviceUpdateOne) RemoveAuditLogIDs(ids ...int64) *CodexManagedDeviceUpdateOne {
	_u.mutation.RemoveAuditLogIDs(ids...)
	return _u
}

// RemoveAuditLogs removes "audit_logs" edges to CodexDeviceAuditLog entities.
func (_u *CodexManagedDeviceUpdateOne) RemoveAuditLogs(v ...*CodexDeviceAuditLog) *CodexManagedDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuditLogIDs(ids...)
}

// Where appends a list predicates to the CodexManagedDeviceUpdate builder.
func (_u *CodexManagedDeviceUpdateOne) Where(ps ...predicate.CodexManagedDevice) *CodexManagedDeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexManagedDeviceUpdateOne) Select(field string, fields ...string) *CodexManagedDeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexManagedDevice entity.
func (_u *CodexManagedDeviceUpdateOne) Save(ctx context.Context) (*CodexManagedDevice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexManagedDeviceUpdateOne) SaveX(ctx context.Context) *CodexManagedDevice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexManagedDeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexManagedDeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexManagedDeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexmanageddevice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexManagedDeviceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := codexmanageddevice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := codexmanageddevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Arch(); ok {
		if err := codexmanageddevice.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.arch": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManagerVersion(); ok {
		if err := codexmanageddevice.ManagerVersionValidator(v); err != nil {
			return &ValidationError{Name: "manager_version", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.manager_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := codexmanageddevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CodexManagedDevice.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexManagedDevice.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodexManagedDevice.api_key"`)
	}
	return nil
}

func (_u *CodexManagedDeviceUpdateOne) sqlSave(ctx context.Context) (_node *CodexManagedDevice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexmanageddevice.Table, codexmanageddevice.Columns, sqlgraph.NewFieldSpec(codexmanageddevice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexManagedDevice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexmanageddevice.FieldID)
		for _, f := range fields {
			if !codexmanageddevice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexmanageddevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codexmanageddevice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(codexmanageddevice.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Arch(); ok {
		_spec.SetField(codexmanageddevice.FieldArch, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagerVersion(); ok {
		_spec.SetField(codexmanageddevice.FieldManagerVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(codexmanageddevice.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(codexmanageddevice.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(codexmanageddevice.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(codexmanageddevice.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(codexmanageddevice.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.UserTable,
			Columns: []string{codexmanageddevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.UserTable,
			Columns: []string{codexmanageddevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.APIKeyTable,
			Columns: []string{codexmanageddevice.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codexmanageddevice.APIKeyTable,
			Columns: []string{codexmanageddevice.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.TokensTable,
			Columns: []string{codexmanageddevice.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdevicetoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuditLogsIDs(); len(nodes) > 0 && !_u.mutation.AuditLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   codexmanageddevice.AuditLogsTable,
			Columns: []string{codexmanageddevice.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codexdeviceauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodexManagedDevice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexmanageddevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
