// Code generated by ent, DO NOT EDIT.

package codexdeviceauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLTE(FieldID, id))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldDeviceID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldUserID, v))
}

// Event applies equality check predicate on the "event" field. It's identical to EventEQ.
func Event(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldEvent, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldDeviceID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldUserID, vs...))
}

// EventEQ applies the EQ predicate on the "event" field.
func EventEQ(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldEvent, v))
}

// EventNEQ applies the NEQ predicate on the "event" field.
func EventNEQ(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldEvent, v))
}

// EventIn applies the In predicate on the "event" field.
func EventIn(vs ...string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldEvent, vs...))
}

// EventNotIn applies the NotIn predicate on the "event" field.
func EventNotIn(vs ...string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldEvent, vs...))
}

// EventGT applies the GT predicate on the "event" field.
func EventGT(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGT(FieldEvent, v))
}

// EventGTE applies the GTE predicate on the "event" field.
func EventGTE(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGTE(FieldEvent, v))
}

// EventLT applies the LT predicate on the "event" field.
func EventLT(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLT(FieldEvent, v))
}

// EventLTE applies the LTE predicate on the "event" field.
func EventLTE(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLTE(FieldEvent, v))
}

// EventContains applies the Contains predicate on the "event" field.
func EventContains(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldContains(FieldEvent, v))
}

// EventHasPrefix applies the HasPrefix predicate on the "event" field.
func EventHasPrefix(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldHasPrefix(FieldEvent, v))
}

// EventHasSuffix applies the HasSuffix predicate on the "event" field.
func EventHasSuffix(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldHasSuffix(FieldEvent, v))
}

// EventEqualFold applies the EqualFold predicate on the "event" field.
func EventEqualFold(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEqualFold(FieldEvent, v))
}

// EventContainsFold applies the ContainsFold predicate on the "event" field.
func EventContainsFold(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldContainsFold(FieldEvent, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldContainsFold(FieldIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.CodexManagedDevice) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexDeviceAuditLog) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexDeviceAuditLog) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexDeviceAuditLog) predicate.CodexDeviceAuditLog {
	return predicate.CodexDeviceAuditLog(sql.NotPredicates(p))
}
