// Code generated by ent, DO NOT EDIT.

package codexmanageddevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldAPIKeyID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldPlatform, v))
}

// Arch applies equality check predicate on the "arch" field. It's identical to ArchEQ.
func Arch(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldArch, v))
}

// ManagerVersion applies equality check predicate on the "manager_version" field. It's identical to ManagerVersionEQ.
func ManagerVersion(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldManagerVersion, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContainsFold(FieldPlatform, v))
}

// ArchEQ applies the EQ predicate on the "arch" field.
func ArchEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldArch, v))
}

// ArchNEQ applies the NEQ predicate on the "arch" field.
func ArchNEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldArch, v))
}

// ArchIn applies the In predicate on the "arch" field.
func ArchIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldArch, vs...))
}

// ArchNotIn applies the NotIn predicate on the "arch" field.
func ArchNotIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldArch, vs...))
}

// ArchGT applies the GT predicate on the "arch" field.
func ArchGT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldArch, v))
}

// ArchGTE applies the GTE predicate on the "arch" field.
func ArchGTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldArch, v))
}

// ArchLT applies the LT predicate on the "arch" field.
func ArchLT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldArch, v))
}

// ArchLTE applies the LTE predicate on the "arch" field.
func ArchLTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldArch, v))
}

// ArchContains applies the Contains predicate on the "arch" field.
func ArchContains(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContains(FieldArch, v))
}

// ArchHasPrefix applies the HasPrefix predicate on the "arch" field.
func ArchHasPrefix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasPrefix(FieldArch, v))
}

// ArchHasSuffix applies the HasSuffix predicate on the "arch" field.
func ArchHasSuffix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasSuffix(FieldArch, v))
}

// ArchEqualFold applies the EqualFold predicate on the "arch" field.
func ArchEqualFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEqualFold(FieldArch, v))
}

// ArchContainsFold applies the ContainsFold predicate on the "arch" field.
func ArchContainsFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContainsFold(FieldArch, v))
}

// ManagerVersionEQ applies the EQ predicate on the "manager_version" field.
func ManagerVersionEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldManagerVersion, v))
}

// ManagerVersionNEQ applies the NEQ predicate on the "manager_version" field.
func ManagerVersionNEQ(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldManagerVersion, v))
}

// ManagerVersionIn applies the In predicate on the "manager_version" field.
func ManagerVersionIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldManagerVersion, vs...))
}

// ManagerVersionNotIn applies the NotIn predicate on the "manager_version" field.
func ManagerVersionNotIn(vs ...string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldManagerVersion, vs...))
}

// ManagerVersionGT applies the GT predicate on the "manager_version" field.
func ManagerVersionGT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldManagerVersion, v))
}

// ManagerVersionGTE applies the GTE predicate on the "manager_version" field.
func ManagerVersionGTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldManagerVersion, v))
}

// ManagerVersionLT applies the LT predicate on the "manager_version" field.
func ManagerVersionLT(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldManagerVersion, v))
}

// ManagerVersionLTE applies the LTE predicate on the "manager_version" field.
func ManagerVersionLTE(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldManagerVersion, v))
}

// ManagerVersionContains applies the Contains predicate on the "manager_version" field.
func ManagerVersionContains(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContains(FieldManagerVersion, v))
}

// ManagerVersionHasPrefix applies the HasPrefix predicate on the "manager_version" field.
func ManagerVersionHasPrefix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasPrefix(FieldManagerVersion, v))
}

// ManagerVersionHasSuffix applies the HasSuffix predicate on the "manager_version" field.
func ManagerVersionHasSuffix(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldHasSuffix(FieldManagerVersion, v))
}

// ManagerVersionEqualFold applies the EqualFold predicate on the "manager_version" field.
func ManagerVersionEqualFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEqualFold(FieldManagerVersion, v))
}

// ManagerVersionContainsFold applies the ContainsFold predicate on the "manager_version" field.
func ManagerVersionContainsFold(v string) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldContainsFold(FieldManagerVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldStatus, vs...))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotNull(FieldLastSeenAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.FieldNotNull(FieldRevokedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTokens applies the HasEdge predicate on the "tokens" edge.
func HasTokens() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TokensTable, TokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokensWith applies the HasEdge predicate on the "tokens" edge with a given conditions (other predicates).
func HasTokensWith(preds ...predicate.CodexDeviceToken) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := newTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuditLogs applies the HasEdge predicate on the "audit_logs" edge.
func HasAuditLogs() predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuditLogsTable, AuditLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditLogsWith applies the HasEdge predicate on the "audit_logs" edge with a given conditions (other predicates).
func HasAuditLogsWith(preds ...predicate.CodexDeviceAuditLog) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(func(s *sql.Selector) {
		step := newAuditLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexManagedDevice) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexManagedDevice) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexManagedDevice) predicate.CodexManagedDevice {
	return predicate.CodexManagedDevice(sql.NotPredicates(p))
}
